### ISSUE TITLE
Inserting/Updating records to all pool cluster

### ISSUE THREAD

**Issue by ritesh-nitw** [mysqljs/mysql#1457]
I am using four databases server in production. The read operations can be performed from any random  host, while insertion or update need to be performed on all databases in the pool. 

I used [pool cluster](https://github.com/mysqljs/mysql#poolcluster) to add all databases into pool. However, whenever I update record/or insert, the record is added/updated to only one of the database. Is it possible to write across all using this module?

Thanks,
Ritesh

**Comment by sidorares** [comment]
is there any reason why you don't use replication on the server?

**Comment by dougwilson** [comment]
Right, @sidorares. I'm going to close the issue, as adding this to the pool cluster is just not going to work, because it's just not a best practice in any way, if only that you could never have any defaults, auto_increment columns, and more, since there is no way to keep them in sync.

The purpose of a pool cluster is to setup for use with replication servers.
