### ISSUE TITLE
Enable formatting nested arrays for bulk updates

### ISSUE THREAD

**Issue by ycjcl868** [mysqljs/mysql#1461]
I want to do bulk updates easily:
```
var arr = [];
for(var i = 0; i < studentIDs.length;i++){
	arr.push([parseInt(grades[i]),parseInt(studentIDs[i]),parseInt(courseID)]);
}
connection.query('update chooseCourse set grade=? where studentID in (select id from student where studentID = ?) and courseID = ?',[arr],function(err,result){
	console.log(results);  //error
	if(results.affectedRows){
		//do something
	}
})
```
but there're  errors. the results is undefined and Cannot read property 'affectedRows' of undefined.

**Comment by dougwilson** [comment]
AFAIK there is no such thing as bulk updated in MySQL. Can you show me what you are expecting the generated SQL to look like?

**Comment by ZJONSSON** [comment]
Is it possible that the pattern best suited here is a bulk upsert with either
INSERT ... ON DUPLICATE KEY UPDATE 
http://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html

REPLACE INTO
http://dev.mysql.com/doc/refman/5.7/en/replace.html

Both of them rely on the primary key or a unique index.  So as long as you can design a unique index around the keys to update (and dont mind inserts when the keys dont exists) then you can get very efficient execution (the sql would be very different from the example above)

**Comment by dougwilson** [comment]
Hi @ZJONSSON, yes, if you do bulk inserts (and bulk upserts are the same syntax as inserts) then you can use a single `?` to format these types of queries. There is still, AFAIK, no way to do bulk updates, which is what the original question was.

@ycjcl868 if you meant bulk upserts (or they are OK for your use-case) @ZJONSSON has the answer for you above :) Otherwise if you are talking about update only, I'm not sure there is a solution, but if you can make a pull request or something, we can always take a look!
