### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by dadixon** [mysqljs/mysql#1464]
For the life of me I can't connect to my localhost mysql server. I keep getting the ECONNREFUSED error message. 

```js
var connection = mysql.createConnection({
    host     : 'localhost',
    user     : 'root',
    password : '',
    // socketpath: '/Applications/MAMP/tmp/mysql/mysql.sock',
    database : 'embraced'
});
```

**Comment by dougwilson** [comment]
Hi @dadixon, perhaps check your firewall or something? I'm not really sure if we can be of much help here, as the error `ECONNREFUSED` is coming from Node.js core, saying that the TCP connection was refused when trying to connect to port 3306 (in your example) on whatever IP `localhost` resolves to on your machine.

Can you tell me what happens when you run the following command?
```
$ node -e "require('net').createConnection(3306)"
```

**Comment by dadixon** [comment]
I figured it out. I had to put in the port number and that worked.

**Comment by dougwilson** [comment]
Ah, good to hear, @dadixon!

**Comment by mm-wang** [comment]
I'm having a similar problem with connecting to a socket. The socket I would like to connect to is a google cloud proxy for a google sql server. According to [Google Cloud SQL's help page for external connections](https://cloud.google.com/sql/docs/external#proxy), the UNIX socket follows the path ``<PROXY_PATH>/<INSTANCE_CONNECTION_NAME>``. I am using this path as the socketPath, and am using the correct username and password. I can connect if I use the node command you provided above. Any other thoughts?
