### ISSUE TITLE
In not working?

### ISSUE THREAD

**Issue by nofear87** [mysqljs/mysql#1467]
a part of my query:

`WHERE id IN (?)`

when i pass the args ("1,143,45")

it's not working correctly....any ideas?

**Comment by dougwilson** [comment]
Hi @nofear87, I assume when you say your passing the args ("1,143,45"), you mean you are giving an array with the single string `"1,143,45"`, i.e., your call may look like the following:
```js
connection.query("SELECT * FROM table WHERE id IN (?)", ["1,143,45"])
```

So your issue is that you want to actually pass in an array where each item (number in your case) is it's own array element. Example:
```js
connection.query("SELECT * FROM table WHERE id IN (?)", [[1,143,45]])
```

**Comment by nofear87** [comment]
Works....thanks!
