### ISSUE TITLE
ER_HOST_IS_BLOCKED

### ISSUE THREAD

**Issue by nhongf** [mysqljs/mysql#1477]
Hi,

I got this issue when the number of users increased in my site. Can you provide any clue of the cause from this screenshot please.
![screen shot 2016-04-06 at 2 52 32 pm](https://cloud.githubusercontent.com/assets/6456895/16942992/5f4142ce-4dc3-11e6-9156-eeae40b7a177.png)

**Comment by Tomino2112** [comment]
We just got the same error, no user increase, using default settings for mysql pool

**Comment by dougwilson** [comment]
Hi folks, that error itself is coming from your MySQL server; this module simply wraps it in an `Error` object and exposes it to you. Without using third-party tools from Percona (which I don't think are free), I'm not sure if there is a good way to find out why your server blocked the host.

If you wanted to talk generically, the most common ways I've seen this happen is if your code is using `connection.destroy()` instead of `connection.end()`, if your code does not end the connections before closing the process, or a firewall between your Node process and MySQL server keep breaking the TCP connections.

**Comment by dougwilson** [comment]
I'm going to close this issue, since I think I explained it above and there hasn't been any reply to it to do anything further.
