### ISSUE TITLE
Too Many Connection error

### ISSUE THREAD

**Issue by bgobi1991** [mysqljs/mysql#1490]
Hi Team,
I am using mysql create pool method but still connection is opened status.

so after connection reached "Too Many Connection error"

**Comment by dougwilson** [comment]
Hi @bgobi1991, that's really weird, and haven't really hard of it before. I played around a bit today and couldn't reproduce. Can you provide the code you are using and the instructions for me to reproduce the issue? Alternatively, since you have access to an environment that is having the issue, would you be willing to put together a PR with a fix?

**Comment by dougwilson** [comment]
Hi @bgobi1991 since I haven't heard back in a few months, I'm going to close the issue.
