### ISSUE TITLE
How to debug Error - Unable to execute database query-Error: Cannot enqueue Query after fatal error.

### ISSUE THREAD

**Issue by nirmalgoswami** [mysqljs/mysql#1492]
Hello,

I know this is little stupid question at first but i am getting following error only some time

`unable to execute database query-Error: Cannot enqueue Query after fatal error.`

i want to solve issue but before solve issue we need to replicate issue but i am facing above issue less time only 5-6 time in last 3 month but i dont know how to replicate issue.

Thank you,
Nirmal Goswami

**Comment by sidorares** [comment]
Hi @nirmalgoswami ! You need to add error handler to your connection object and create new connection once you see error. Or, better, use connection pool

**Comment by nirmalgoswami** [comment]
Hi @sidorares Thanks for reply.I have already error handler thats why i am able to get error but question is how to replicate issue :)

**Comment by sidorares** [comment]
Well, you need to add the code in the error handler to discard connection (and maybe do some other cleanup or create a new connection)

**Comment by dougwilson** [comment]
Hi @nirmalgoswami it's hard to really answer without seeing your code. I'm going to close the issue since there hasn't been any follow up for a couple months.

Perhaps I can add a bit of explanation for what the error means that may help:

The `Error: Cannot enqueue Query after fatal error` error is an error that occurs when you call `connection.query` on a dead `connection` object. The connection specifically died due to a "fatal error". What specifically that fatal error was you'd have to tell us, as it would have been emitted on the connection object prior to the `Error: Cannot enqueue Query after fatal error` error at some point (the error object would have a `fatal` property set to `true`).

Some common fatal errors are TCP connection disruptions, either from the MySQL closing the connection for idling for longer than what you configured your MySQL server to allow, or some accidental network hiccup (a router rebooting, firewall restarting, something).
