### ISSUE TITLE
Escaping issue

### ISSUE THREAD

**Issue by NegativeIQ** [mysqljs/mysql#1494]
```js
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : '',
  database : 'goodfon',
  charset  : 'utf8'
});
connection.connect();

var sql="REPLACE INTO `Images` (`Title`, `Tags`, `Thumb`, `Category`, `Resolution`, `Uploader`, `Colors`) VALUES ('??','??','??','??','??','??','??')"; 
	var inserts=[listing.title, listing.tags, listing.thumb, listing.category, resolution, listing.uploader, testColor];
	sql = mysql.format(sql, inserts);
```
Table is utf8 (utf8_general_ci) and inserted rows are like these:
```
`2140x123`
`Город`
`www`.`mywall`.`com/wallpaper/yahty-korabli-pirs-prichal-more`.`html`
```

**Comment by dougwilson** [comment]
Hi @NegativeIQ! Don't worry, I fixed your markup :) From reading your question, I'm not 100% sure if I interpreted it right, but I believe you are saying that you expected a column to contain the value `www.mywall.com/wallpaper/yahty-korabli-pirs-prichal-more.html`, but instead the column contains the value `` `www`.`mywall`.`com/wallpaper/yahty-korabli-pirs-prichal-more`.`html` ``, correct?

If this is the case, then I think the issue is just in how you are using `??` for escaping instead of using the `?`. You see, `??` is for escaping identifiers, while the `?` is for escaping values. Can you try out the following and see if that fixes your issue?
```js
var sql="REPLACE INTO `Images` (`Title`, `Tags`, `Thumb`, `Category`, `Resolution`, `Uploader`, `Colors`) VALUES (?,?,?,?,?,?,?)"; 
    var inserts=[listing.title, listing.tags, listing.thumb, listing.category, resolution, listing.uploader, testColor];
    sql = mysql.format(sql, inserts);
```

**Comment by NegativeIQ** [comment]
Yes, problem is with value being totally wrong with that extra apostrophes everywhere.

If i use single question mark for escaping i get these error (i also copy pasted your code just in case)
`Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1`

And by the way i have to escape all the columns since they are all user input one way or another.

**Comment by dougwilson** [comment]
Hi @NegativeIQ, can you paste here what `mysql.format(sql, inserts);` results in when you run your code? Since you didn't give complete code, I'm really just guessing a lot here (and there is a language barrier ;) ), so please bear with me.

**Comment by NegativeIQ** [comment]
Ok, just debuged raw sql string after format and found the problem. testColor is actually an array, silly me...
Thx for help.
