### ISSUE TITLE
add `.query` to poolNamespace

### ISSUE THREAD

**Issue by alsotang** [mysqljs/mysql#1505]
Now poolNamespace can only use with

```js
var pool = poolCluster.of('SLAVE*', 'RANDOM');
pool.getConnection(function (err, connection) {});
pool.getConnection(function (err, connection) {});
pool.query // !!!not a function
```

Its behavior is some different from `Pool`. With `Pool` we can use `.query` directly.

```js
var pool  = mysql.createPool({
  connectionLimit : 10,
  host            : 'example.org',
  user            : 'bob',
  password        : 'secret',
  database        : 'my_db'
});

pool.query('SELECT 1 + 1 AS solution', function(err, rows, fields) {
  if (err) throw err;

  console.log('The solution is: ', rows[0].solution);
});
```

**Comment by dougwilson** [comment]
I don't see any reason why not to add it :) Feel free to work up a pull request, otherwise I can get around to it at some point :)!

**Comment by alsotang** [comment]
OK, since you think it's ok, I would work for it this weekend. : )

**Comment by merarischroeder** [comment]
I recommend forcing the use of Promise

```
static getConnection() {
	db.initialisePool();
	return new Promise((resolve, reject) => {
		db.pool.getConnection((err, connection) => {
			if (err) {
				connection.release();
				reject(err);
			}
			else {
				resolve(connection);
			}
		});
	});
}

static query(connection, query, params) {
	return new Promise((resolve, reject) => {
		connection.query(query, params, function (err, rows) {
			if (err) {
				if (!inTransaction) {
					connection.release();
				}
				reject(err);
			}
			else {
				resolve(rows);
			}
		});
	});
}

queryPromise(qry) {
	var state = {
		connection: null,
	};
	return db.getConnection().then((connection) => {
		state.connection = connection;
		return db.query(state.connection, query.queryString, query.queryParams, true);
	}).then((data) => {
		state.connection.release();
		return data;
	}).catch((error) => {
		state.connection.release();
		throw error;
	});
}
```

**Comment by alsotang** [comment]
The usage of Promise seems another topic than poolNamespace @merarischroeder

**Comment by merarischroeder** [comment]
I don't think you need a committee to return a Promise from a new function. You can have both a Promise and non-promise API for the .query function. 

Whether or not the final internal implementation uses Promises or not, is beside the point. But, why not use this as an opportunity to explore that?

Public Access:

- .query(sql, callback) - wraps .queryPromise
- .queryPromise(sql).then(dataCallback).catch(errorCallback)

Why not both? [https://www.youtube.com/watch?v=vqgSO8_cRio](https://www.youtube.com/watch?v=vqgSO8_cRio)

**Comment by sidorares** [comment]
> Why not both?

`connection.query()` currently returns `Query` command object, and some code may rely on this

We could potentially add extra top level `createConnectionPromise()` and `cretePoolPromise()` helpers that would return promise wrappers (this is already part of [mysql2 api](https://github.com/sidorares/node-mysql2/blob/master/documentation/Promise-Wrapper.md) )

**Comment by merarischroeder** [comment]
but .query can be the same API, and .queryPromise is the new API.

RE: Wrappers. That's beside the point. We could be using Promises internally, and exposing two styles of public access. Or is the problem backward compatibility, that there is no support of Promises in prior popular version of nodejs?

**Comment by sidorares** [comment]
> We could be using Promises internally

Switching to promises internally is a lot of refactoring with no immediate benefit. Why do you think it worth doing? Internal code does not have complicated async task flow, I can't see where promises would fit well. And you are right about node versions, we still support node 0.8 and this might be critical for some users

**Comment by merarischroeder** [comment]
> Switching to promises internally is a lot of refactoring with no immediate benefit

This would only be done in the new function.

> Why do you think it worth doing?

They're the future. There's no need to refactor all the code. But you can certainly start with new functions.

But that's beside the point now:

Check out line 188 in https://github.com/mysqljs/mysql/blob/master/lib/Pool.js, apparently this function is already there.

**Comment by dougwilson** [comment]
Hi @merarischroeder, I think the should promises be used internally isn't really even an option. This module supports all the way down to Node.js 0.6, and Promises never even existed in Node.js until around 0.11.x, so just the internal usage of promises would lock out all those versions from users for just the reason of "someone felt like using promises instead of callbacks internally" right? Doesn't seem like the appropriate trade off to drop Node.js version support to me.

> Check out line 188 in https://github.com/mysqljs/mysql/blob/master/lib/Pool.js, apparently this function is already there.

This issue is about the `PoolNamespace`, as you can see in the title and initial description. That does not have a `.query` method. The code you are pointing to is not related to `PoolNamespace`. @alsotang has already put together a PR to add this method, it was just pending some unit tests right now.

I hope that makes sense for what this issue is actually about :)

**Comment by merarischroeder** [comment]
As I said before: "Or is the problem backward compatibility?"

> This module supports all the way down to Node.js 0.6

So I take that as a yes.

>  would lock out all those versions from users for just the reason of "someone felt like using promises instead of callbacks internally" right

Probably, but not necessarily. What I am suggesting is an internal use, near the surface of the public API interface, not deep within. It would be as simple as only adding the function if the Promise object is detected to exist OR by testing Node.js >= 0.11.

I would have thought, such code is acceptable. You should continue supporting older versions, but you can easily support newer features if newer Node.js is being run. NodeJS is up to v6.6, and Promises have been around since 0.11 as you noted. That's a long time to wait, to include Promise support in this mysql module.

Promises are the future of nodejs. Don't hold back mysql module, especially when there's a workable solution.

**Comment by dougwilson** [comment]
> Don't hold back mysql module, especially when there's a workable solution.

I'm not, but I just haven't seen anyone offer up a workable solution. If you can put a pull request together that demonstrates this as a work-able solution, please, please do! Even Node.js core doesn't provide a promise interface for some reason. I'm not holding back, but certainly the fact that I don't use promises and I don't see any pull requests with implementations coming in `¯\_(ツ)_/¯`

Also, if you want to continue this further, there is at least one open issue about Promises already. Let's not hijack this thread for the following reasons:

(1) going off-topic on a thread means the original posted is getting all these emails unrelated to their original issue.
(2) this conversation ends up hiding the original issue, causing more divergent conversation.
(3) it's hard for people to discover this conversation to participate in, because the conversation does not match the issue of the title, excluding users from the conversation.
(4) this issue will be closed with the original issue is resolved, causing all this useful conversation to be lost into the abyss of closed issues.

**Comment by merarischroeder** [comment]
@dougwilson I'll stick to working on one feature at a time.

> I don't see any reason why not to add it :) Feel free to work up a pull request, otherwise I can get around to it at some point :)!

In another thread, you noted that .query is in the code. Did this happen very recently since your quote?

> Let's not hijack this thread

I'm not that annoying :)

We're only discussing Promises, because that's the API I recommended for this feature. Although there may be  a Promises thread _context_ is crucial. (eg. Is the glass half full or half empty? It depends if you're filling it or drinking from it). ie. Your discussion in that thread probably doesn't relate to isolated public interfaces.

**Comment by dougwilson** [comment]
Please stop derailing this thread re: Promises. I'm going to lock this thread, because promises have nothing to do with the original issue, and the original issue already has an open PR. Tis issue will be closed with the merging of that PR.

**Comment by dougwilson** [comment]
PR #1506 merged!
