### ISSUE TITLE
Feature: Tracking of borrowed pool connections

### ISSUE THREAD

**Issue by merarischroeder** [mysqljs/mysql#1528]
Glossary:
- **Available** connection is in the pool (and may or may not be an idle connection)
- **Borrowed** connection is one that has not been released nor `.end`'d

Problem:
- The default behaviour of the pool is that getConnection will never return if the pool is exhausted and Borrowed connections are never released (by one or more code paths)
- The caller doesn't know this occurs

Solution:

My strategy is **information-first** - allow the coder to inspect a borrowed list and determine if there's a problem. This is the MVP. But here's a fuller suite of development that I recommend:
- Register connection into Borrowed list, when getConnection yields a connection
- Remove from the Borrowed list, when .Release is called (also for .End ?)
- Add BorrowedAt meta-data to the connection object, so the coder can enumerate Borrowed list and report when there are old connections in there beyond a threshold
- Add Lifetime field { Permanent, Longer , Short } - which helps the coder enumerate the Borrowed list
- Add Context field - which allows any data, such as a string, 'Report for Finance'
- Add internal support for the Lifetime field - if it's Permanent, create a new connection, not from the pool, but still include in the Borrowed list. If it's Longer or Short, Borrow out from the pool as usual.
- Internal checking of Short/Longer Borrowed connections. If Short connection persists for more than 10 seconds, trigger a public event "Expire". This needs to be handled by the external user, if they want to properly log any expiries and thereby find connection-pool leaks.
- getConnection timeout - the callback will be fired and err parameter set, if connection cannot be obtained within timeout limits
- getConnection fail by default - if the connection pool is exhausted - I think this is already possible.
- inline .query function which wraps the complexity of getConnection and .release, so the caller can't forget.

Any other ideas? Are there any weaknesses in my suggestion?

**Comment by dougwilson** [comment]
Hi @merarischroeder, great stuff! I've mostly read through it all and I have a few comments below. When do you think you'll be able to get started on making some pull requests to implement this stuff?

> getConnection timeout - the callback will be fired and err parameter set, if connection cannot be obtained within timeout limits

:+1: 

> getConnection fail by default - if the connection pool is exhausted - I think this is already possible.

Yep, it is already possible, but setting the queue size to zero. Obviously it would be a major version bump to change it from where it is today (infinity), and the number would have to actually be something reasonable that would not cause simple DoS vectors against a website (defaulting to no queue would easily do that).

> inline .query function which wraps the complexity of getConnection and .release, so the caller can't forget.

Doesn't this already exist? How is this different from the current `pool.query` method?

**Comment by merarischroeder** [comment]
> When do you think you'll be able to get started on making some pull requests to implement this stuff?`

Good question. I would start with just Borrowed list with no other features to begin with. Give me a week and give me a prod, if it hasn't happened yet.

> Doesn't this already exist? How is this different from the current pool.query method?

That's embarrassing, I didn't realise that was there. I assumed it wasn't.

**Comment by dougwilson** [comment]
> Good question. I would start with just Borrowed list with no other features to begin with. Give me a week and give me a prod, if it hasn't happened yet.

Cool. I know you laid out some things around this, and I didn't really comment on them, mainly because I don't fully understand what you're asking for, so I very much look forward to seeing some kind of work in progress code to understand what your proposal is around this :) I don't know if/what makes sense for this module (which is a low-level driver module, not a ORM) because I don't really grasp what you are suggesting and how it would be used. I'd probably better understand if I can see the code example and code examples of using the feature, which would be apparent in the PR :)

> > Doesn't this already exist? How is this different from the current pool.query method?

> That's embarrassing, I didn't realise that was there. I assumed it wasn't.
 
Oh, haha :) I guess when you start working on a pull request, you'll get more familiar with the module :)

**Comment by merarischroeder** [comment]
> which would be apparent in the PR

True. Let the code speak.

Say, do I need to write tests for this as well?

**Comment by merarischroeder** [comment]
@dougwilson 

I have NEVER done a fork - PR before. What do you expect?

I have already forked, and was going to just make the change locally, then hoped I could simply send you the PR. Any branches required in my fork to make it easier?

**Comment by dougwilson** [comment]
> Do I need to write tests for this as well?

Yea, usually the general PR for any GitHub project is to (1) have working code (2) add all applicable tests for the change if the project has tests (this does) and (3) add documentation for the changes if the project has documentation in the repo (this does).

Those are just the very simple ones. I mean, we're here to work with you on the PR, so you can't exactly "do it wrong" as we'll provide feedback to help during the process :)

> Any branches required in my fork to make it easier?

There isn't, but it's good practice to always make a branch and work on it. The reason is you can then make multiple PRs, try out different things on different branches, etc. Once you make a PR, if you make it on your `master` branch, as long as the PR is open, you cannot touch your fork, as any changes in `master` will automatically appear in the PR. If you use a different branch, it's a lot easier to manage this. Ultimately it's whatever you're most comfortable with.

**Comment by merarischroeder** [comment]
> Let the code speak.

Proof of concept done: https://github.com/merarischroeder/mysql/commit/1e7855c8969442015ac89aaf53e8eddeecd04e9e

It's not run/tested yet. But you get the idea. 

Feedback please.

After my approach survives critique, I'll move ahead with testing.

**Comment by dougwilson** [comment]
Ah, I think I understand what you're thinking. I think there is a current open issue proposing exactly what you are trying to do, and I think it's been even more fleshed out. I'll have to take a look through the issues tomorrow to see which one. I think from what I remember, the idea was to do it using events instead of internal tracking, especially because it's less overhead for people who do not need that tracking and also makes it easier to write the code that would actually use that feature.

Can you provide some kind of code demonstration of exactly how a real-world application would would use the API you made in your PoC? That would help a lot in trying to flesh out the API.

**Comment by merarischroeder** [comment]
@dougwilson A simple config setting could enable the feature. It would make most sense to me for the `pool` to internally track what is currently borrowed.

```
//...
pool.config.trackBorrowedConnections = true;
//...
function findNeglectedConnections(pool)
{
    var neglected = [];
    var bc = pool.BorrowedConnections;
    var d = new Date();
    var expiredThreshold = d.setHours(d.getHours() - 2);

    for (var i = 0; i < bc.length; i++)
    {
        if (bc[i].borrowedAt < expiredThreashold)
        {
            neglected.push(bc[i]);
        }
    }
   return neglected;
}

var neglectedSet = findNeglectedConnections(pool);
console.log('Neglected connections:');
for (var i = 0; i < neglectedSet.length; i++)
{
    console.log(neglectedSet[i].borrowedAt + ': ' + neglectedSet[i].context);
}
```

**Comment by dougwilson** [comment]
Ah, @merarischroeder, I see. I mean, obviously the pool already tracks that (it does that because it keeps a list of all connections and a list of free connections; borrowed is the intersection of those two lists, easy to derive). So looking at your example code, I think for what you are trying to do, determine if there is a neglected connection after a certain period of time, an event interface would be a lot better & more efficient, because I assume what you're going to do is constantly call `findNeglectedConnections()` in your code over and over again, in the hopes that at one point it will find something. An event-based system would not require that type of polling mechanism. I'll see what I can put together as an example some time this week for you :)

**Comment by dougwilson** [comment]
It looks like this is probably a duplicate of the issue #1366 ?

**Comment by dougwilson** [comment]
Also may be a duplicate of issue #1449

**Comment by merarischroeder** [comment]
Have just made an updated with the config:
https://github.com/merarischroeder/mysql/commit/4399f438b350cb9d6020a005ee950a273949ce13

> An event-based system would not require that type of polling mechanism.

There is no way around it, ultimately you need to poll something like findNeglectedConnections. There is no event in the pool which would trigger when an arbitrary amount of time has elapsed since borrowing. So there would need to be a setInterval for checking. But the standards for expiry are completely dependent on the application, which is why findNeglectedConnections would be external to mysql module, but borrowedConnections would be a function from the pool.

>  intersection of those two lists

If there's only a pool of 100, and you only check ever 10 mins, then an intersection will work when the caller calls pool.getBorrowedConnections(). But if there's more and/or the call to getBorrowedConnections is several times a second, then it's different. I suspect the former is fine though, and that a calculated intersection would be acceptable.

**Comment by dougwilson** [comment]
> There is no way around it, ultimately you need to poll something like findNeglectedConnections. There is no event in the pool which would trigger when an arbitrary amount of time has elapsed since borrowing. So there would need to be a setInterval for checking. But the standards for expiry are completely dependent on the application, which is why findNeglectedConnections would be external to mysql module, but borrowedConnections would be a function from the pool.

I don't agree, which is why I want to show some code, if you can please wait a couple days for me to write it to show you my idea, like you are sharing your ideas with me :)

**Comment by dougwilson** [comment]
Also, can you evaluate those possible duplicate issues? We should move this conversation into one of those issues if they are the same issue, because over time, people subscribe to issues on GitHub, and talking on those issues keep those users involved in the conversation.

**Comment by merarischroeder** [comment]
> Also, can you evaluate those possible duplicate issues

Sure, but I do need more than 8 minutes to finish posts, read through threads, etc.

I see with #1449, you can setTimeout upon borrowing from the pool. But that would require an optional parameter to be added to getConnection, so the application can specify a per-call timeout length. There should also be a global config, which when set, specifies a fall-back timeout value.

**Comment by dougwilson** [comment]
> Sure, but I do need more than 8 minutes to finish posts, read through threads, etc.

Sorry I'm just responding as fast as you are, my bad :) I'm heading off for the night, so you're free to take as long as you need. I'll try to circle back around sometime tomorrow :) !

**Comment by dougwilson** [comment]
P.S. while we were talking I wrote up https://github.com/mysqljs/mysql#contributing which should help give some initial information for you and future people who have never made a PR :) I was trying to get it finished tonight so you'd be able to read it overnight :) !

**Comment by dougwilson** [comment]
So I was able to whip up an example really quick (I need to go to sleep already :S) to demonstrate how I would envision an event-based system. The following shows a _non-polling_ implementation by a user based on events that will simply `console.log` a message. This can very easily be extended to do a lot more (like read a context property on the connection, store the time the connection was acquired, etc.):
```js
// PoC example for how an event-based tracking would function
// when creating the pool, call
// trackPoolConnections(pool, 600000 /* 10 mins */)
// to get alerts on long-standing connections
function trackPoolConnections(pool, limit) {
  var connections = new Map();
  pool.on('acquire', function (conn) {
    connections.set(conn, setTimeout(function () {
      console.log('Connection %d acquired past limit!', conn.threadId);
    }, limit));
  });
  pool.on('release', function (conn) {
    clearTimeout(connections.get(conn));
    connections.delete(conn);
  });
}
```

**Comment by merarischroeder** [comment]
Thanks @dougwilson 

I just implemented that in one of my projects. However, I will be simply adding a property to the connection object. (I also chose to have a callback, and use arrow functions of course)

```
static trackPoolConnections(pool, limit, cb) {
      pool.on('acquire', (conn) => {
        conn.timoutHandle = setTimeout(() => { cb(conn); }, limit);
      });
      pool.on('release', (conn) => {
        if (conn.timoutHandle) clearTimeout(conn.timoutHandle);
      });
}
```
