### ISSUE TITLE
support MySQL functions in query values

### ISSUE THREAD

**Issue by SeregPie** [mysqljs/mysql#1542]
Hello. I just started using node.js and your mysql module is very helpful. I like the query values feature but I cannot use it if I have functions and variables in the query. Why not implement an extra class which will be not escaped?

``` javascript
escape(/*...*/) {
    if (value instanceof MysqlFunc) {
        return value.toString();
    } else {
        //... as usual
    }
}

let sql = 'INSERT INTO user SET ?';
let user = {name: 'Alex', created: connection.mysqlFunc('now()')};
connection.query(sql, user, (err, result) => {
    //...
});
```

**Comment by dresende** [comment]
This is something I already thought of. `sqlstring` module could, instead of ignoring functions, just call them (perhaps passing connection handler) and synchronously replace function return string. Although your example is not actually useful (since you can define a date as current timestamp by default) there are many useful functions one could use, not just for insert statements.

**Comment by dougwilson** [comment]
Yea, this is already in progress and a solution is supposed to be in the next release of this module next week.

**Comment by dougwilson** [comment]
We have a PR in sqlstring that needs some touch up and then I planned on landing it over this weekend.

**Comment by mr-moon** [comment]
Any news on this?
