### ISSUE TITLE
Is it possible to execute a query for every connection in a pool?

### ISSUE THREAD

**Issue by straube** [mysqljs/mysql#1560]
To disable MySQL's `autocommit`, I'm executing the following query every time a connection is established:

```
SET autocommit = 0
```

However, I couldn't find a way to manually commit the data on ending the connection. When I'm not using a connection pool, I can simply run the query before calling `connection.end()`. I looked through the library source code and it seems there is no `end` event or something like that.

Is it possible to execute a query for every connection in a pool before disconnecting?

**Comment by dougwilson** [comment]
By "before disconnecting", do you mean you want to run this when you call `pool.end()` or something else?

**Comment by straube** [comment]
Something like this. I'd like to run `COMMIT` for every connection, just before calling `pool.end()`. I guess if there was a way to iterate over all connections, I could do that.

Thanks for the fast reply, BTW.

**Comment by dougwilson** [comment]
Gotcha. One problem with that is a connection can drop off at anytime while it is idling in the pool, and so if you put the connect back into the pool without committing first, then you can silently loose anything done over that connection. Connections can drop due to network issue, server idle timeouts, etc.
