### ISSUE TITLE
[Suggestion] Always include fields parameter in Readme.md

### ISSUE THREAD

**Issue by KernelDeimos** [mysqljs/mysql#1577]
I was using this module in conjunction with async, and they conveniently both follow the standard of passing (err, result) to the callback. However, after looking at one of the examples, I mistakenly expected only two arguments (err, rows) to be passed to a callback created by async, which caused a very confusing result.

I think it's very convenient to use this module with async, and many people probably do so, so this might save a lot of confusion for anybody who also runs into this problem.

**Comment by dougwilson** [comment]
Hi @KernelDeimos typically JavaScript code, people only put the argument names that are actually in use, instead of listing all of them. In fact, I believe it was another PR that went through the README and removed them in the first place, as it cased a lot of confusion. The documentation is large, and the entire section dedicated to explaining how queries work clearly show the three arguments: https://github.com/mysqljs/mysql#performing-queries

**Comment by dougwilson** [comment]
You're welcome to create a PR to add them back to all the callbacks, though, and I'll merge it back in. Please add in comments in all the code to say something so someone doesn't come make a PR removing them again :)

**Comment by KernelDeimos** [comment]
Oh, that's a good point actually. I'll make a PR and I think I'll actually just add a note to be careful instead of changing anything. Would there by anything against explicitly mentioning async as an example?

**Comment by dougwilson** [comment]
> Would there by anything against explicitly mentioning async as an example?

i.m.o. I would rather have the right words in there that does not mention `async` module such that we're not bias to a particular module. The reason is because people may use a different one, and if we don't provide the words in order for people to understand what is happening, the docs will only be useful to the subset of folks who are using mysql + async, leaving out the others. I think that if we can get some good documentation that explains what is happening, people will be able to understand how to connect two modules together in a way that can be applied to any integration, instead of only against `async`.

**Comment by KernelDeimos** [comment]
I submitted a PR that adds one warning about this. Alternatively, maybe a "Common Mistakes" section could be added, and this note could be referenced from several examples.

**Comment by dougwilson** [comment]
I've tried that before, it turns into an endless list, and people will keep making issues complaining about how the issue they had wasn't in there. I think it's better just to provide the proper documentation vs. trying to figure out every possible combination of every possible module people will use.
