### ISSUE TITLE
Select with the function CHAR return a buffer type object

### ISSUE THREAD

**Issue by jacklamcm** [mysqljs/mysql#1587]
When using the function CHAR in a select statement, a buffer type object is returned.
Using toString function of buffer class can give a wanted result.
My node version is 6.9.1 and mysql version is 5.5.53.

My current work around is to use CONVERT function to declare the field as char.

**Comment by dougwilson** [comment]
Hi @jacklamcm this is because it is how the `CHAR()` function works in MySQL server.

Docs at http://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_char

> By default, CHAR() returns a binary string. To produce a string in a given character set, use the optional USING clause: 
> mysql> SELECT CHARSET(CHAR(X'65')), CHARSET(CHAR(X'65' USING utf8));

You'll need to add the `USING` clause to get a non-binary string returned. In this module, binary data is represented as `Buffer` instances.
