### ISSUE TITLE
Handling transitions with multiple servers

### ISSUE THREAD

**Issue by smileapplications** [mysqljs/mysql#1588]
I have two databases located in two different servers that i need to INSERT INTO and UPDATE one after the other in the same web service that i have created with Hapi.js. 

Is it possible to use transaction, commits and rollbacks with two different connections ?

Example
- Start connection with DB1
   - Start transaction with DB1
       - Insert values in DB1.table
       - Update values in DB1.table
   - Start connection with DB2
       - Start transaction with DB2
                   - Insert values in DB2.table
       - If everything went well COMMIT DB1 and COMMIT DB2
       - If an error occurrent ROLLBACK DB1 and ROLLBACK DB2
    - End connection DB2
- End connection DB1

I tried with normal connections but i saw that as soon as i connect to DB2 the connection with DB1 is lost

**Comment by dougwilson** [comment]
Hi @smileapplications since MySQL itself does not support transactions spanning multiple servers, you'll have to make two separate transactions and try to commit / roll them back manually based on error / success conditions (though you'll still end up with an unsolvable edge case of thinking you should commit, and the first commit is successful but the second fails, and now you cannot roll back the first since it was already committed).

If you are using the pool, you'll just need to use two pools: one for each server. If you are manually creating connections, you just need to create two connections, one to each server.

**Comment by smileapplications** [comment]
Ok thanks. I'll try to use a single database then...

**Comment by dougwilson** [comment]
Sounds good, @smileapplications ! Let me know if there were any additional questions :)
