### ISSUE TITLE
Incorrect arguments when selecting an email

### ISSUE THREAD

**Issue by vnheros** [mysqljs/mysql#1609]
I want to check if an email exist or not.
I tried 2 ways:
Way 1:
```js
connection.query('SELECT * FROM emailtable WHERE email = ? ', [inputemail], function(err, rows, fields) {
if (err) throw err;
....
});
```

Way 2:
```js
var query = "SELECT * FROM emailtable WHERE email=" + mysql.escape(inputemail);
connection.query(query, function(err, rows, fields) {
if (err) throw err;
...
});
```
In which inputemail = abc@xyz.com
But I got error in both ways:
```
node_modules\mysql\lib\protocol\Parser.js:78
        throw err; // Rethrow non-MySQL errors
        ^
Incorrect arguments
```

How I can avoid this ???

**Comment by dougwilson** [comment]
Hi @vnheros the stack you are seeing there is Node.js pointing to where the last `throw` statement was, not where the error is coming from. You see, when that particular throw is called, it is because there was an error thrown by your code within the callback you supplied and we caught it so we could make sure to clean up our internals before continuing the error throw.

What is throwing the incorrect arguments I'm not sure, but it's something you're calling in your callback. If you're not seeing the full stack trace printed, consider doing the following to see it:
```js
connection.query('SELECT * FROM emailtable WHERE email = ? ', [inputemail], function(err, rows, fields) {
if (err) throw err;
try {
....
} catch (e) {
  console.log('error! ' + e.stack)
}
});
```
