### ISSUE TITLE
can I use values() function directly from mysqljs

### ISSUE THREAD

**Issue by shivarajnaidu** [mysqljs/mysql#1610]
Can I use values() function like shown below?
```
  connection.query('INSERT INTO todos VALUES  ?', data, (err, row) => {
          console.log(row)
   });
```
where data is an array which consists objects (array of objects)...
Can i directly map this to value function?
So that I can insert multiple records in single query.

or is there any other way to insert multiple records just like values (....), (....), (....) function do ?
if no solution for it then please consider above semantic. It will be very helpful

**Comment by dougwilson** [comment]
You cannot today, it only accepts arrays of arrays. The biggest issue to accepting object is that (1) we don't know in which order to actually put the columns such that they end up correct in the database and (2) it's complicated when you provide a bunch of objects where not all have the same keys since the `VALUES()` in SQL wants them all to be the same length.

**Comment by shivarajnaidu** [comment]
Thanks for your response :+1:
