### ISSUE TITLE
Sockets leak with domain

### ISSUE THREAD

**Issue by vietthang** [mysqljs/mysql#1619]
I'm currently using mysql 2.12.0 and encountered an issue with socket leaks.

This is the screenshot of heapdump output:
<img width="1241" alt="screen shot 2017-01-10 at 7 40 58 am" src="https://cloud.githubusercontent.com/assets/1080481/21789516/333e826c-d708-11e6-95a1-f4b8dc1aab41.png">

After investigate, I found that on `Connection.prototype.connect` function, the sockets are added to a global domain but have never been removed. It can be fixed/hacked temporarily by set `usingDomains` to `false` globally.

Please take a look.

**Comment by dougwilson** [comment]
When you use domains in your app (which would be why Node.js has using domains set to true), then you need to make sure you have a domain set during the connect that represents the lifetime of your request. If there is some other solution, please submit a PR, as I don't really understand domains fully, so really wouldn't know how to fix. Thanks!

**Comment by dougwilson** [comment]
Also, for maybe myself and anyone else who wants to take a look, we would need to know all the following:

1. The version of Node.js
2. The version of this module
3. A full program that anyone can run the reproduces the issue.
4. Full instructions on how to run the program and how to know the issue is happening and a description of what should happen when there is no issue.

**Comment by vietthang** [comment]
I also don't understand about `Domain` very much. This is actually the first time I heard about it. As far as I can tell, I saw the code which add the socket(s) into domain but didn't see the code to remove they. I can take a deeper look into it.

About my environment:
1. Version of Node.js: 6.2.2 run on AWS Elastic Beanstalk(Linux)
2. Version of Module: 2.12.0.

I'm going to submit the program & instructions later.

**Comment by dougwilson** [comment]
Great! And domains don't work where they remove anything; you're supposed to manage the lifetime of the domain and `.dispose()` of it yourself when done.

**Comment by vietthang** [comment]
This is example code:

```
const mysql = require('mysql')
const domain = require('domain')

// enter domain
domain.create().enter()

setInterval(
  () => {
    const connection = mysql.createConnection({
      host: 'localhost',
      user: 'root',
      password: ''
    })

    connection.query('SELECT 1', (error) => {
      connection.end((error) => {
        console.log('Leaked member count:', process.domain.members.length)
      })
    })
  },
  100
)
```

Explained: when using domain then create & terminate connections repeatedly, the number of member in global domain object increase continuously, even when the connections are terminated.

Expected: the number of socket in domain should be reduced when connections terminated.

Solution: remove socket from its domain when terminated/error. I can submit a pull request, can you help me where I should hook into to provide the remove function.

**Comment by dougwilson** [comment]
Does the same issue happen if you replace `mysql.createConnection` with `net.createConnection`?

**Comment by dougwilson** [comment]
It looks like they should be attached, though the code `domain.members` only lists out the explicitly bound objects, not including all the implicitly bound objects (a new event emitter will implicitly bind to the active domain). It looks like emulating implicitly bound is not documented well in Node.js, so this module is attempting to re-bind the internal sockets (which are event emitters) to the remembered domain using the documented explicit binding API.

As far as I can tell, removing them from domain on end / error is definitely the wrong solution, because that won't stop a future `error` event from potentially being raised on the removed event emitter, crashing the application. It looks like the correct solution would be to fix the emulation to correctly emulation the implicit binding, which does not create the circular references that are causing the memory leaks (i.e. it should not appear in the `domain.members` array like all the other emitters being implicitly bound to the domain)

**Comment by vietthang** [comment]
Nope. The sockets are only added to the global domain when `connect` called by following code.

```
    // Connect socket to connection domain
    if (Events.usingDomains) {
      if (this._socket.domain) {
        this._socket.domain.remove(this._socket);
      }

      if (this.domain) {
        this.domain.add(this._socket);
      }
    }
```

which locates in `lib/Connection.js:94`. Because of that, I can hack it by forced `usingDomains` to false. :)

**Comment by vietthang** [comment]
Ahh I understand now.

**Comment by vietthang** [comment]
From node.js official documentation `https://nodejs.org/api/events.html#events_error_events`,

```
If an EventEmitter does not have at least one listener registered for the 'error' event, and an 'error' event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits.
```

And in the library code:

```
this._socket.on('error', this._handleNetworkError.bind(this));
```

Seems like the library already have handler for "error" event. So it likely would not crash application on error and the domain usage for error handling is irrelevant, right?

**Comment by dougwilson** [comment]
Having the socket attached to the domain does more than just catch unhandled error events. It also is how the listeners on the socket events end up executing within the proper domain (see https://github.com/nodejs/node/blob/master/lib/events.js#L177 from the Node.js source code). If the socket is not attached to the proper domain, then none of it's event handlers would run in the proper domain as well.

You're certainly welcome to experiment with various solutions :) There is a pretty comprehensive domains test suite in this module, so you can easily experiment with different solutions and see if our tests still pass or not :)

**Comment by vietthang** [comment]
I've just submitted a PR to fix this issue at https://github.com/mysqljs/mysql/pull/1620. Please review when you have time. Thank you.

**Comment by sithmel** [comment]
We are having the same issue in our project.

It looks like removing the domain in the "end" and "destroy" methods works the same.
For example:
```
Connection.prototype.end = function end(options, callback) {
  ...
  this._implyConnect();
  this._protocol.quit(opts, bindToCurrentDomain(cb));
  this.domain.remove(this._socket); // here
};
```
I can't judge if this is any better of @vietthang PR.
