### ISSUE TITLE
[Question] Is there any Error Event for Pooling Connection?

### ISSUE THREAD

**Issue by raghav196** [mysqljs/mysql#1663]
Is there any error event to catch fatal errors for pooling connections like there is one for the connection object.

I tried using 
```js
var pool  = mysql.createPool({
  connectionLimit : 10,
     host            : mysqlHost,
     user            : mysqlUser,
     password        : mySqlPassword,
     database        : mysqlDb
});

pool.on('error', function(err) {
     console.log(err); 
});
pool.query('USE name_of_db_that_does_not_exist');
```
but it doesn't work.

**Comment by dougwilson** [comment]
Hi @raghav196 this is how the pool is designed, which follows what happens when you make a query without a callback that is an error without the pool. If you want to actually get the error, you need to either (a) provide a callback to the query or attach an `error` event listener to the Query object returned by `pool.query` method.

I hope this helps!
