### ISSUE TITLE
ER_PARSE_ERROR 

### ISSUE THREAD

**Issue by sasidhar678** [mysqljs/mysql#1666]
`connection.query('CALL SP_InsertUser("name","email",@uid); SELECT @uid;', callback);`

The above code snippet is throwing the below error,

ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT @uid' at line 1

**Comment by dougwilson** [comment]
Hi @sasidhar678 the reason your MySQL server is encountering a syntax error is because you probably did not set the `multipleStatements` connection option to `true`. You can see a list of all the connection options at https://github.com/mysqljs/mysql#connection-options and in particular a discussion on how to do multiple queries at https://github.com/mysqljs/mysql#multiple-statement-queries
