### ISSUE TITLE
Using time zone without setting it manually 

### ISSUE THREAD

**Issue by dorshay6** [mysqljs/mysql#1680]
Hey wanted to see if there is any better to this thing :)
```js
var con = mysql.createConnection({
  "connectionLimit" : 5,
  "host" : "localhost",
  "user" : "root",
  "password" : "",
  "database" : "test",
  "timezone" : "Asia/Jerusalem",
  "dateStrings": true
});

con.query('SET time_zone = \'Asia/Jerusalem\';', function(err) {
  if(err) throw err;
});
```

**Comment by dougwilson** [comment]
Well, if that is the contents of your query callback, then you can just leave it off, making it:
```js
var con = mysql.createConnection({
  "connectionLimit" : 5,
  "host" : "localhost",
  "user" : "root",
  "password" : "",
  "database" : "test",
  "timezone" : "Asia/Jerusalem",
  "dateStrings": true
});

con.query('SET time_zone = \'Asia/Jerusalem\';');
```

In reality, all the `timezone` parameter does is have you specify the time zone your MySQL server it set to. So that means that calling `SET time_zone` is completely unnecessary if you just set the `timezone` parameter to the timezone your MySQL instance is configured for.

**Comment by dorshay6** [comment]
My SQL is set to UTC, the beaver that I was expecting from this plugin is to set it automatically because of `"timezone" : "Asia/Jerusalem"`

**Comment by dougwilson** [comment]
Yes, the docs didn't really explain what is was far. I expanded the documentation for the timezone option 👍
