### ISSUE TITLE
Updating large amount of rows

### ISSUE THREAD

**Issue by antoinelanglet** [mysqljs/mysql#1691]
Hello,

I'm trying to update a million raws with fake names. 

```js
server.route({
  method: 'PUT',
  path: '/faker',
  config: {
    validate: {

    },
    pre: [
      require('./client')
    ]
  },
  handler: (request, response) => {
    let nb_rows;
    let firstname;
    let lastname;
    request.pre.client.query('SELECT COUNT(*) as rows FROM clients', function (error, results, fields) {
      if (error) throw error;
      let nb_rows = results[0].rows;
      for(let i = 1; i <= nb_rows;i++) {
        let firstname = faker.name.firstName();
        let lastname = faker.name.lastName();
        request.pre.client.query('UPDATE clients SET firstname = ?, lastname = ? WHERE ID = ?', [firstname, lastname, i], function (error, results, fields) {
          if (error) throw error;
        });
        if (i == nb_rows) {
          process.stdout.write("Update completed.\n")
        }
        else {
          process.stdout.write('Updating rows -> ' + i/(nb_rows/100) + '% complete...\r');
        }
      };
    });
  }
});

```
The problem is, it is going through the 1 million rows, but in my database it's only updating around 10,000 rows each times, and it is not throwing me any error in the terminal. I've tried to expand the max_connections limit of MySQL but that doesn't change anything.

Any ideas of what I might be doing wrong ?
Thanks.

**Comment by dougwilson** [comment]
Hi @antoinelanglet if the `nb_rows` variable holds that 1 million number, I would suspect that since you are writing your code to queue up 1 million queues all at once, you're likely running into a v8 GC issue, perhaps even a complete allocation failure within v8.

I would suggest writing your for loop to work in series rather than trying to queue 1 million UPDATE queries inside your Node.js process:
```js
      function iterate(i) {
        if (i > nb_rows) {
          process.stdout.write("Update completed.\n")
        }
        else {
          process.stdout.write('Updating rows -> ' + i/(nb_rows/100) + '% complete...\n');
          updateClient(i, iterate.bind(null, i+1));
        }
      }
      function updateClient(i, next) {
        let firstname = faker.name.firstName();
        let lastname = faker.name.lastName();
        request.pre.client.query('UPDATE clients SET firstname = ?, lastname = ? WHERE ID = ?', [firstname, lastname, i], function (error, results, fields) {
          if (error) throw error;
          next();
        });
      }
      iterate(1);
```

**Comment by kai-koch** [comment]
If you use InnoDB as engine, I suggest you using transactions and commit e.g. 50.000 rows at once instead of 50.000 single row. But you got to configure mysqljs to accept "multiple line statments" and you need to escape the values manually.

That should take care of the I/O of the DBMS being the bottleneck, and queing up ridiculous ammounts of single row queries in memory. Depending on your source of input, node makes the row-queries faster than MySQL can recceive and write them to disk.

I suggest using something similar to what dougwilson wrote, but instead of waiting for each single update-row-query to finish, use a transactions and make "packages" of e.g. 50.000 Update-rows at once. Less Disk I/O and less traffic between mysqljs and mysql.

**Comment by antoinelanglet** [comment]
Thank you very much for your quick response, @dougwilson.

Thank you also because your methods worked !

There are two things however that I don't fully understand here : 

1. On the allocation failure within V8. I had an allocation failure before, as my for loop wouldn't even go to 1 million but stopped at around 600,000 because of an allocation failure. So I increased the `--max-old-space-size`, and didn't come across that issue anymore. Is that related to what you said about the V8 ?

2. At the end, we're still making a kind of a loop, aren't we ? So how this method prevent Node.js queuing 1 million row ?

**Comment by kai-koch** [comment]
Dougs method makes the next Update-Statement when the previous is finished.

Your method made them all at once without waiting them to return. Which results in large memory allocation because V8 needs to keep track of each single query.

**Comment by antoinelanglet** [comment]
Thank you for your explanation :)
