### ISSUE TITLE
Join operation for two different database tables on different server

### ISSUE THREAD

**Issue by codingmaven** [mysqljs/mysql#1696]
Is there any way to use the join operation for two tables from different databases?
Both databases are on different server.

**Comment by dougwilson** [comment]
No, this is just a basic MySQL driver that lets you send MySQL protocol commands to the servers. This means it only supports what MySQL itself supports, which does not include your use-case unfortunately. If MySQL were to ever add such a feature, you could use it with this module. Otherwise, you'll have to make two separate queries to the two servers and then manually perform the join logic within Node.js.

**Comment by codingmaven** [comment]
As far as I know, this is possible with mysql

https://dev.mysql.com/doc/refman/5.7/en/federated-usagenotes.html
http://stackoverflow.com/questions/5698378/mysql-join-between-tables-in-2-different-databases
http://stackoverflow.com/questions/5832787/mysql-joins-between-databases-on-different-servers-using-python

**Comment by dougwilson** [comment]
Then all you have to do is connect to the database that has access to both and simply run the query. Are you experiencing an error when trying to do that? Any query you run on the MySQL command line client should run through this module as well, as it just sends the query to the database to run.

**Comment by codingmaven** [comment]
My databases are in different server

**Comment by dougwilson** [comment]
Right. So, I'm confused with what your trying to do. The SO post was pretty clear on what you needed to do, so not sure what the issue is?

Either

(1) Connect to both servers, perform the two queries, and manually join in your Node.js server

or

(2) Create a table with the FEDERATED storage engine on one of your servers that has access to both serves and then use this module to connect to the server with the FEDERATED storage engine table and perform your query on that.
