### ISSUE TITLE
Please help: Unknown column 'NaN' in 'field list'".

### ISSUE THREAD

**Issue by AlaDyn172** [mysqljs/mysql#1716]
CODE: https://pastebin.com/EuTd0n5S
ERROR: https://pastebin.com/ncE6H26k

Thanks for helping!

**Comment by dougwilson** [comment]
The error is because in a query you are sending to the server contains a field name of `NaN`, which is not a field in the table you are querying against. I'm sure you don't mean to use a column name of `NaN`, so likely one of the variables you are building your SQL with is `NaN`. If you add `debug: true` to your `createPool` function, re-run and post the output, we can identify what query is being built wrong.

**Comment by AlaDyn172** [comment]
Lol, you helped me a lot, dude.
With debug true I could see what column was NaN.
2 columns were NaN because I tried to column1++; and column2++;, but the variables were:
var column1; and var column2; that's why, and I switched to var column1 = 0; and var column2 = 0;, and now it's working. Thanks!

**Comment by dougwilson** [comment]
No problem! Glad yo got it working :)

**Comment by wengeezhang** [comment]
Maybe the generated query string contains NaN for a column value (not column name).  this also throw error:Unknown column 'NaN' in 'field list'"
