### ISSUE TITLE
ERR_ACCESS_DENIED_ERROR Windows

### ISSUE THREAD

**Issue by yadderace** [mysqljs/mysql#1747]
Hi, I have a problem, I create an API REST and I use Ubuntu to develop my project, everything was fine, but when I want to develop on windows I have the error: **ER_ACCESS_DENIED_ERROR: Access denied for user** for each connection that I tried to do.

I have the same configuration for database connection but I dont understand why I get the error. Please any could help me. Sorry for my bad english.

**Comment by dougwilson** [comment]
Hi @yadderace that denied error is from your MySQL server. Can you show what the grant tables look like?

**Comment by hdseba33** [comment]
Hi @yadderace and @dougwilson 
I have the same problem. The user that adds has all the permissions.-

**Comment by dougwilson** [comment]
Hi @hdseba33 can you paste the grant tables for the user and the full error message you're getting?

**Comment by hdseba33** [comment]
of course
```
error: {
code: "ER_ACCESS_DENIED_ERROR",
errno: 1045,
sqlMessage: "Access denied for user 'voragine_root'@'host.voragine.com.ar' (using password: YES)",
sqlState: "28000",
fatal: true
}
```

**Comment by hdseba33** [comment]
![permission](https://user-images.githubusercontent.com/29787989/29953579-dc768544-8ea7-11e7-9474-a37ccb1eb6c2.png)

**Comment by dougwilson** [comment]
@hdseba33 please show the grants for that user. SQL to run: `SHOW GRANTS FOR 'voragine_root'@'host.voragine.com.ar'`. MySQL assigns Grants on a per-connecting-host basis.

**Comment by hdseba33** [comment]
access denied for user ....

**Comment by dougwilson** [comment]
Hi @hdseba33 I'm not able to help if you can't show the Grants. Just ran that command as `root` or whatever super user you administrate the server with.

**Comment by hdseba33** [comment]
thanks

**Comment by hdseba33** [comment]
Okay, anything I'll tell you how it was
thanks

**Comment by dougwilson** [comment]
The denied error is from your MySQL user because your have the user `'voragine_root'` without any Grants when connecting from host `'host.voragine.com.ar'`. Either grant that user some permissions on the `'%'` host or the specific host `'host.voragine.com.ar'` to fix your issue. The `SHOW GRANTS` will show you want Grants the user has and you can use the `GRANT` command to add some Grants to that user and host combination (you may need to `FLUSH PRIVILEGES` after your `GRANT` command).
