### ISSUE TITLE
Select Not working with AND

### ISSUE THREAD

**Issue by Gaurav-Ambasta** [mysqljs/mysql#1756]
I am running query 
connection.query({
                                sql: "SELECT * FROM `user_entry_catalogue` WHERE `upc` = ? AND `user_id` = ?",
                                timeout: 40000,
                                values: { user_id: user.uid, upc: payload.upc }
                            }, function (error, results, fields) {

but getting error as mentioned below. How to use AND in select query.

message:"ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `upc` = '12345' AND `user_id` = ?' at line 1"

**Comment by bbito** [comment]
I'm not experienced with this directly, but my understanding of the placeholder mechanics from the [Escaping query values](https://github.com/mysqljs/mysql/blob/master/Readme.md#escaping-query-values) section of the readme leads me to believe that your problem stems from your placeholder values being key/value pairs in an object rather than just the values in an array.
perhaps try:
```
connection.query({
  sql: "SELECT * FROM user_entry_catalogue WHERE upc = ? AND user_id = ?",
  timeout: 40000,
  values: [user.uid, payload.upc]
}, function (error, results, fields) {...
```

**Comment by bbito** [comment]
I just realized that the placeholders are out of order in my suggestion above, you'd want to try this instead:
```
connection.query({
  sql: "SELECT * FROM user_entry_catalogue WHERE upc = ? AND user_id = ?",
  timeout: 40000,
  values: [payload.upc, user.uid]
}, function (error, results, fields) {...
```

**Comment by dougwilson** [comment]
Yea, the values proper has to be an array; there is no support for using an object.
