### ISSUE TITLE
connection.release dosen't work

### ISSUE THREAD

**Issue by shuaishenk** [mysqljs/mysql#1804]
I use the connectionPool,and set the connectionLimit to 10,and I write connection.release()  in the callback of connection.query. While the count of the sleep thread of mysql  is more than 10 upto 50 .And destroy   can solve the problem but it will spend more time to create new connection.So how do I solve the problem.

**Comment by dougwilson** [comment]
Hi @shuaishenk weird indeed. We have a lot of tests for the release and it seems to work, so in general not sure what the issue would be. Can you share the following?

1. Version of Node.js you're using
2. Version of this module you're using.
3. Complete code that will reproduce the issue we can run
4. Instructions for how to run the code and how to validate the issue is occurring

Thanks!

**Comment by shuaishenk** [comment]
@dougwilson I have found the problem of my code.And It works well now. 
 Thank you~
