### ISSUE TITLE
How to INSERT/UPDATE BigNumbers?

### ISSUE THREAD

**Issue by dskvr** [mysqljs/mysql#1815]
There's a little note about what happens when this module _reads_ a BigNumber from a MySQL database, but I can find now information about to `INSERT` or `UPDATE` a BigNumber. I assumed that if I passed a BigNumber object, that this module would convert it to it's appropriate format, but I've tested countless potential workarounds without success. 

Can this module write BigNumbers back to the database? If so, how?

**Comment by dougwilson** [comment]
Hi @dskvr sorry I didn't see this somehow. Just sorting through all the issues right now.

So that's a good question -- I don't think it's ever been asked before. Obviously if your query has a big number in the string it'll work fine (i.e. `UPDATE tbl SET col = 875357274537262222`). If you're trying to use the escaping functions, they don't understand big numbers, so since JavaScript itself cannot represent `875357274537262222` as a number (`console.log(875357274537262222)` shows `875357274537262200`) that means of course that `"UPDATE tbl SET col = " + mysql.escape(875357274537262222)` is not correct.

What variable type are you using to represent the BigNumbers in JavaScript currently?

**Comment by kai-koch** [comment]
You insert the bignumber as string in JavaScript.
MySQL will type cast and write it as big number into the table.

Example:
```JavaScript
var x = new BigNumber('875357274537262222');
var query = 'UPDATE tbl SET col = ' + mysql.escape(x.toString);
```

The query send to the server will look like this:
UPDATE tbl SET col = '875357274537262222'
MySQL will take care of type casting.

I close this for now, feel free to ask, should there be further questions about this.
