### ISSUE TITLE
error event not listen in pool connection

### ISSUE THREAD

**Issue by shivshankar3578** [mysqljs/mysql#1840]
mysql @latest
i'm trying to create event base modular structue using mysql 
below snippet works fine for me
```
global.DB = mysql.createConnection(mysqlParams) 
DB.query("select * from wrong_table")
DB.on("error", (err)=>{
   console.log(err)
})
```
bu when i'm trying using this not works
```
global.POOL = mysql.createPool(mysqlParams) 
POOL.query("select * from wrong_table")
POOL.on("error", (err)=>{
   console.log(err)
})
```
form doc 

> Since the pool.query method is a short-hand for the pool.getConnection -> connection.query -> connection.release() flow, calling pool.end() before all the queries added via pool.query have completed, since the underlying pool.getConnection will fail due to all connections ending and not allowing new connections to be created.

i just want to collect errros of whole app to one place. callbacks are good with express but need to use event base architecture. anyone help pls

**Comment by dougwilson** [comment]
Hi @shivshankar3578 the pool does not emit error events. The only events emitted by the pool are the ones documented in https://github.com/mysqljs/mysql#pool-events . I can help to figure out what you need to do, if you can describe what your issue is / what exactly you're trying to achieve :)

**Comment by shivshankar3578** [comment]
i update question may be more informatic

**Comment by dougwilson** [comment]
Ah. So if you want to collect error on all the connections, attach a connection event listener to the pool, and then within that attach an error listener to the connection. Then everytime a new connection is made, you'll get your error listener added to it to log.

**Comment by shivshankar3578** [comment]
oh thanks. this works for me
```

POOL.on('connection', function (conn) {
	conn.on("error", (err)=>{
		 console.log(err)
	})
});
POOL.query("select * from wrong_table")
```

**Comment by ronny332** [comment]
Sorry for reusing this old post, but maybe a short answer solves my issue and this would avoid a further ticket ;-).

The last answer is easy to use and working (shivshankar3578), but, how to fetch errors globally with the connection event fired?

What I in detail mean:
you request a connection and this fails. The calling routine is fetching the error object, but this can be anywhere in my code. You need to handle the error, what of cause has to be one anyway. But at this step you have to handle logging, too.
It would be great to catch the failing information locally within the mysql module/class.

Is this possible, or is this feature missing? I wan't to avoid a long error handling within the normal queries to centralize everything to one point (logging from one point instead of many).
