### ISSUE TITLE
Escape without quotes '

### ISSUE THREAD

**Issue by codedninja** [mysqljs/mysql#185]
I am trying to run a REGEXP in mysql but client.escape() keeps on adding single quotes is there a way around this? Here is an example of the function I am using and the output SQL.

``` javascript
var name = mysqlclient.escape('bag');
var sql = "SELECT `id`,`name`,`price` FROM `items` WHERE `name` REGEXP '[[:<:]]"+bag+"[[:>:]]'";
```

It outputs the following

``` SQL
SELECT `id`,`name`,`price` FROM `items` WHERE `name` REGEXP '[[:<:]]'bag'[[:>:]]'
```

**Comment by redixhumayun** [comment]
I'm seeing the same behaviour with `mysql.escape` where it adds single quotes around the escaped literal. Is there a workaround?

**Comment by dougwilson** [comment]
Instead of
```js
var name = mysqlclient.escape('bag');
var sql = "SELECT `id`,`name`,`price` FROM `items` WHERE `name` REGEXP '[[:<:]]"+bag+"[[:>:]]'";
```

Write it like
```js
var name = 'bag';
var sql = "SELECT `id`,`name`,`price` FROM `items` WHERE `name` REGEXP " + mysqlclient.escape("[[:<:]]"+bag+"[[:>:]]");
```

Even better, use placeholders instead. More information on escaping is at https://github.com/mysqljs/mysql#escaping-query-values

I'm just locking this as resolved as the issue is many, many years old and old issue may or may not be relevant in current versions. Always best to open a new issue and provide a link to an old issue if you believe it is still relevant.
