### ISSUE TITLE
pool.getConnection(callback) not calling callback

### ISSUE THREAD

**Issue by justmobilize** [mysqljs/mysql#1850]
I am using Amazon Aurora and after getting and releasing a handful of connections, a call to `pool.getConnection(callback)` never calls the callback

mysql: 2.15.0
node: 6.11.4

```
var mysql = require('mysql');
var pool = mysql.createPool({
  host: 'xxxx,
  port: 'xxxx',
  user: 'xxxx',
  password: 'xxxx',
  database: 'xxxx',
  multipleStatements: true,
  connectionLimit: 50,
});
  
pool.on('acquire', function (connection) {
  console.log('Connection %d acquired', connection.threadId);
}).on('enqueue', function () {
  console.log('Waiting for available connection slot');
}).on('release', function (connection) {
  console.log('Connection %d released', connection.threadId);
});

var getMoreData = function() {
  setTimeout(() => {
    pool.getConnection(function(err, connection) {
      var q = 'SELECT * FROM table where id>' + lastId ;
      connection.query(q).on('result', function(row) {
      connection.pause();
      if (something > 0) {
        connection.resume();
      } else {
        connection.release();
      }
    });
  }, 500);
}
```

After a handful of calls to `getMoreData`, `pool.getConnection` doesn't call the callback and there are no `acquire` or `enqueue` logs

**Comment by dougwilson** [comment]
If you don't unpause the connection before releasing, it will stay in a paused state. Does unconditionally unpausing the connection fix your issue?

**Comment by justmobilize** [comment]
It doesn't, also a bunch of special casing since result will then fire on the resume.

**Comment by dougwilson** [comment]
Gotcha. So that was the issue when I ran that code you gave above. Is that the exact code you are having an issue with?

**Comment by dougwilson** [comment]
And if you're wondering how I got it to work (since your code wasn't actually a working example), I changed `something` to `Math.random() < 0.5`, just set a const `const lastId = 0` and then added `setInterval(getMoreData, 2000)` at the bottom to keep it going.

**Comment by dougwilson** [comment]
Another thing I noticed when I did that was that `connection.release();` would get called multiple times on the connection, since you're calling `connection.release();` potentially before the query ended and don't have any code to not release it again. I just ran a query that returned a couple rows for me.

I can take another look if you can provide some additional information, perhaps a code example I don't have to adjust to get to run, some data to load into the database that it runs against and instructions for how to reproduce the issue. Then we'll be more likely to be experience the same issue, so what I can track down may be able to resolve your issue.

If you have another idea instead for what the next steps should be, let me know as well :) !

**Comment by pavanmehta91** [comment]
I've the same issue. Can't seem to get connection from the pool Here's my code snippet. The callback is not called or called after several minutes and the behavior is not consistent. Sometimes it gets the connection immediately..




`function executeQueryFromPool(pool, rawQuery, cb) {
console.log('****** getting connection from pool***');
pool.getConnection(function(err, connection) {
console.log("***** executing query from pool connection");
 connection.query(rawQuery, function(err, results) {
        console.log('***********************************************QUERY RETURNED WITH RESULTS');
        connection.release();
    if (err) {
      debug("query", err);
      var e = err;
      cb({
        status: false,
        error: e
      });
    } else {
      cb({
        status: true,
        content: results
      });
    }
  });
});
}
`
