### ISSUE TITLE
idea about transport

### ISSUE THREAD

**Issue by GoNode5** [mysqljs/mysql#1856]
I use websockets to transfer data from Mysql/Node to client.
If a webapp/client ask for a list. I do a simple  "SELECT * FROM posts WHERE title=" hallo"" 
the request is send to Mysql and the client gets an Json.

- Mysql respond (protocol?) to node.js
- Nodejs convert response to ? Object
- Nodejs convert object to Json
- Nodejs send to client via protocol (Http/Websocket)
- client convert Json to Object

Although it mostly very fast I still think there are a lot conversions (4) going on. In Node I'am mostly not interested in the data itself, and I don't care about Json either. The client just needs an Javascript object or Array... that's all...
Any idea how to improve? It's out of my league to suggest protocols like Protobuf. But in general I would like to know your opinions.

**Comment by kai-koch** [comment]
Well, why would want to remove the JSON-layer? There are many good reasons why you want to use a transport-layer like JSON or if you like to e.g. XML.
What is when you want to send data to a non-javascript endpoint? What about security? You want to eval JavaScript objects on the client-side? (Security-Nightmare, just saying.)

If you do not want JSON in node, already you do not need to use it. Node does not convert your result set to JSON, you or the framework, you use, does this. If you want to use some kind of new format to talk to the client-side app, just do it.

Best Practice is not to mingle code-objects with data-objects, for various reasons. (again security one of the more prominent.)

Best Practice is to keep code modular and re-usable. mysqljs does not enforce any transport layer onto your application. How the server-app talks with the client app is strictly up to you, not to node, not to mysqljs. 

Node provides your app different ways to communicate with the client. MySQL provides you a way to communicate with the MySQL-Server, nothing more nothing less.
What you do with the data from the DB-Server is strictly up to you and the other tools and frameworks you use, not to mysqljs or node.

Corrrect me if I am wrong, but the time consuming stuff is the MySQL-Server response and sending the data (in any form) to the client over network, not the 3 conversions that take place in your list. Usually the response and the network-traffic take aeons compared to the conversions, because the conversions are done "in memory".
