### ISSUE TITLE
mysql timestamp values are given bakc as string

### ISSUE THREAD

**Issue by Fuzzyma** [mysqljs/mysql#1895]
I have a coloumn `created_at` whose type is `timestamp`.

When I do this:

```js
const mysql = require('mysql')

var connection = mysql.createConnection({
 // ...
});

connection.connect();

connection.query('SELECT updated_at FROM tablename WHERE id = 1', console.log)
```

I get back a RowDataPacket which includes the `updated_at` coloumn. But its a string!
The option to convert such objects into strings is not passed (should default to false).

Whats wrong here?

**Comment by Fuzzyma** [comment]
Ok I found the issue. I had a null date in the row. Nulldates yield invalid dates when passed to `new Date()`. Imo the behavior should to pass this invalid date to the user and not pass the string instead because that breaks stuff when you are expecting a date.

I now went with nullable dates which are correctly left untouched as null values.

**Comment by dougwilson** [comment]
Hi @Fuzzyma date / time formats that cannot be translated to a JavaScript type are left as their original strings. JavaScript has no method to represent that MySQL "zero date" format -- zero dates are different from the column being NULL, which is why they are not translated to `null` in JavaScript. You can implement a custom type cast (https://github.com/mysqljs/mysql#type-casting) for your date column to cast the zero dates to `null` in JavaScript if that is what works best for your setup -- everyone's setup is different, of course. The goal of the default type casing is to translated as much as possible into JavaScript types without loosing any information (which would happen if zero dates were translated to `null`, because then you wouldn't know if the value in MySQL was `NULL` or a zero date).

I hope that helps!

**Comment by Fuzzyma** [comment]
@dougwilson thx for your fast response. I completely agree with you that a non null coloumn should yield null in javascript. I never said that.

What I said was:
>Nulldates yield invalid dates when passed to new Date(). Imo the behavior should to pass this invalid date to the user and not pass the string

An invalid date is the closest approximation of a mysql zero date you can get because its indeed invalid!
In my opinion the user should get back a date (even if its invalid) because hes waiting for a date.

The exception is of course nullable coloumns - but in this case the user decided about that earlier and knows that this coloumn can return null. A String on the other hand is really unexpected

**Comment by dougwilson** [comment]
Hmm, maybe I misunderstood. Can you show what you mean by what a "Nulldate" is? Maybe we are just thinking different things here.

**Comment by Fuzzyma** [comment]
A zero timestamp is something like `0000-00-00 00:00:00`. A null date is just `NULL` and can only exist when the coloumn is explicitly allowed for NULL values.

The former should return `Invalid Date` which is returned when you do `new Date(0000-00-00 00:00:00)`, the later just `null`.

At the moment you check for invalid dates and when its invalid you return the String value.

**Comment by dougwilson** [comment]
Thanks, sorry for the confusion. Yes, `0000-00-00 00:00:00` is what I'm thinking you were saying, indeed. Exactly, when JavaScript cannot parse the date, the built-in type cast rule is to simply return the date string from the server as-is. You can implement a custom type cast (https://github.com/mysqljs/mysql#type-casting) for your date column to cast the zero dates to null in JavaScript if that is what works best for your setup -- everyone's setup is different, of course.

I looking through the original issue based on `git blame` for the code in question. It looks like the reason this was done is because MySQL allows the date and/or month portions to be zero, but JavaScript will also parse those as Invalid Date. For example, `2005-12-00 23:59:59` is a perfectly valid value in a `DATETIME` column in MySQL but `new Date('2005-12-00 23:59:59') == 'Invalid Date'` and so you'll no longer be able to tell what the original date was out-of-the-box. The goal of the default type casing is to translated as much as possible into JavaScript types without loosing any information.

I hope this makes sense.

**Comment by Fuzzyma** [comment]
To be clear: Null values in databases should be always converted to null in javascript.
However - having a zero date or partial zero date (as in your example) leads to an invalid date (as we both know).
I think our thoughts differ at exactly this point.

In my opinion an invalid date is the exact presentation of something like `0000-00-00 00:00:00` or `2005-12-00 23:59:59`. **Because this dates just dont make any sense** and its valid to give the user back an invalid date in this case.

It seems like you want to give the user the possibility to "recover" a valid date from this invalid date string. However - I know how I can add thas feature when I need it. Thanks!

**Comment by dougwilson** [comment]
I mean, I don't particularly have an opinion either way -- the only opinion I would have would be that a change would have to be in a 3.0 release since it would be breaking. The current behavior was introduced in 2.0, a decision made by the other contributors of the project. From that they laid out the goals of the built-in type casting, which is all I'm just re-iterating here to explain why it is working the way you are seeing.

If I had an opinion at all, I would get rid of type casting all together, because it's not possible to please everyone since everyone seems to have a different opinion on how it should work -- the invalid-date-as-string is what people wanted by filing issues with the project and the project contributors changed to align with what people were asking for.

I think that fielding the endless asks to change this and that about type casting is not worth the time and type casting should simply be removed in 3.0 all together and everything will be returned as the types on the wire protocol level -- strings.

**Comment by Fuzzyma** [comment]
Hehe - I think that wouldnt please others then :).
However - as long as you have typecasting as some sort of plugin available this would be certainly a way to go.

Thanks for the discussion!
