### ISSUE TITLE
connection.end() example in npmjs.org seems to imply synchronous use 

### ISSUE THREAD

**Issue by shulme801** [mysqljs/mysql#1906]
This is a newbie kind of issue.  I used mysql to communicate with a mysql instance on my local host. I followed the examples at https://www.npmjs.com/package/mysql. 

When it was time for my app to close the sql connection, I followed the code example and used connection.end().  Being new to node, I was surprised when code execution marched right along after this connection.end()!  Further research, of course, showed me that I should have used a callback. I recommend that the documentation be updated to show something like this, which does close the connection gracefully: 
```
connection.end(function(err) {
        if (err) throw err;
        console.log("BYE!");
  });

**Comment by dougwilson** [comment]
There is no reason to use a callback in `connection.end()`. You only need to use it if you want to know when the end has completed, as per the docs. Many things in Node.js cause an async action without providing any callback, even in Node.js core itself. This is a standard Node.js coding pattern.

**Comment by shulme801** [comment]
Thanks, Doug. I appreciate the feedback! I really enjoyed using this package, and learned a lot from the wiki.

**Comment by dougwilson** [comment]
No problem! We try to put the examples as the simple / standard use-case to help get started. I don't think I ever use a callback with `connection.end()` since you don't really need to know when it ends, since it'll just automatically happen in the background once called (similar to calling `.end()` on Node.js core socket objects, `.close()` on Node.js core servers, etc.) though it's there in case you want to use it.

Some Node.js core objects (like sockets) don't even provide a callback argument to their `.end()` operations and require listening to an `'end'` event, but we felt like having the optional callback would be slightly simpler than requiring users to register an event listener.
