### ISSUE TITLE
error while trying to run and connect to an external server

### ISSUE THREAD

**Issue by Jaylton** [mysqljs/mysql#1952]
I'm running my app on a remote server, however I'm getting this error when I try to connect to the database:

Error: connect ECONNREFUSED 127.0.0.1:3306 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1189:14) 

my code: 

``var mysql = require('mysql');
var connection = mysql.createConnection({
  host: 'xxxxxxxxx',
  user: 'xxxxx',
  password: 'xxxxxxx',
  database: 'xxxxx'
});
connection.connect();
module.exports = connection;``

When I run the app on localhost it works perfectly, even having to fetch the data on an external mysql server, but when the app is running on an external server it does not work.

Can someone help me?

**Comment by dougwilson** [comment]
Hi @Jaylton this error is coming from Node.js core itself. You can find this error listed in the Node.js documentation along with the explanation for when it happens: https://nodejs.org/api/errors.html#errors_common_system_errors

> ECONNREFUSED (Connection refused): No connection could be made because the target machine actively refused it. This usually results from trying to connect to a service that is inactive on the foreign host.

You'll need to check your firewall and other things to determine what the issue is. It's possible it could be a bug in Node.js itself, but not sure. There isn't a good way to help from this module's code, though.

**Comment by ivenuss** [comment]
Yap, I forgot to run mysql server🤦
