### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:3306的问题

### ISSUE THREAD

**Issue by jdways** [mysqljs/mysql#1961]
how can solve this question,i don't understand why.

**Comment by dougwilson** [comment]
Hi @jdways this error is coming from Node.js core itself. You can find this error listed in the Node.js documentation along with the explanation for when it happens: https://nodejs.org/api/errors.html#errors_common_system_errors

> ECONNREFUSED (Connection refused): No connection could be made because the target machine actively refused it. This usually results from trying to connect to a service that is inactive on the foreign host.

You'll need to check your firewall and other things to determine what the issue is. It's possible it could be a bug in Node.js itself, but not sure. There isn't a good way to help from this module's code, though.
