### ISSUE TITLE
Row Column Mappings are Wrong

### ISSUE THREAD

**Issue by Crowes** [mysqljs/mysql#1990]
I've been facing an issue where one of my `INT` columns was returning as `NaN`, even just as a raw `RowDataPacket`. While I do some custom type casting (for Dates & Boolean), the majority of it is done by the baked-in parser.

Debugging the parser in `RowDataPacket.js` shows that the value it returns for my column is actually that of a different column entirely.

Here, in the debugger (WebStorm), we can see that the `field.name` is `userPrivilege`, and the value is `2017-12-16 14:19:23`. 
https://i.imgur.com/OyWOxjw.png

Here in the table (DataGrip), we can see that the value of `userPrivilege` for this record is `3`, not the date. That date is actually inside `userCreation`.

https://i.imgur.com/eExOstf.png

**Comment by dougwilson** [comment]
Very strange indeed! Definitely I want to take a look and fix this for you. I don't have enough information in order to figure out what is wrong yet. Can you provide as much of the following as possible?

1. Version of this module you are using.
2. Version of Node.js you are using.
3. Distribution name and version of the MySQL server you are using.
4. DDL of the table (or tables of this involves a join) that is being queried.
5. The query that is being run on the table(s).
6. Example data to populate into the table(s) that causes the query to return mixed up columns.

Thank you!

**Comment by Crowes** [comment]
I'll do my best to clarify a bit. 

I've been using an [url=https://github.com/Gallink/Joints/blob/master/parts/DatabaseCasting.js]abstraction[/url] for my type casting, which no longer works. When I reverted to my [url=https://i.imgur.com/aXPjwkH.png]old casting logic[/url] (changed in [url=https://github.com/Gallink/Joints/commit/f1286d3772d58ad837053b37fbc374f349887152]this commit[/url]). I can't spot why -- there's no difference besides placement.

**Version of this Module**: `2.15.0`
**Version of Node.js": `8.1.2` (may be due an update)
**Distribution & Version of MySQL**:  `5.7 Community`
**DDL of the Table**:  https://i.imgur.com/P6ggQFu.png
**Query Being Ran**:  `SELECT * FROM user WHERE userId = ? LIMIT 1` with `["1"]`
**Example Data**: 

      INSERT INTO user (userEmail, userName, userForename, userSurname, userPassword, userDate, userCreation, userToken, userPrivilege, userEnabled)
      VALUES ('james@smith.co.uk', 'Jamesy', 'Matt', 'Smith', '12345', NULL, '2017-12-16 14:19:23', '67c07d70-e26c-11e7-b45d-305a3a0159e0', 3, 1)

**Comment by dougwilson** [comment]
Hi @Crowes that helps a lot and I see the issue in your commit (https://github.com/Gallink/Joints/commit/f1286d3772d58ad837053b37fbc374f349887152). Remember, from our README for typecasting:

> WARNING: YOU MUST INVOKE the parser using one of these three field functions in your custom typeCast callback. They can only be called once.

Well, your date path calls `.string()` two times (once in `_evaluateDate` and then again in `_castDate`), which means that it will end up consuming two columns for dates, otherwise for non-dates consumes a column and ignores is, messing up the offsets.

**Comment by Crowes** [comment]
> Well, your date path calls .string() two times (once in _evaluateDate and then again in _castDate), 

This was changed in the [commit directly afterwards], (https://github.com/Gallink/Joints/commit/d9950acdd8b9a95ccdc58c8dc07de6dae423f7f7#diff-68f3698950cd60d96e4f4bb51b07776d), and did not fix this.

**Comment by dougwilson** [comment]
Hm, weird. Maybe can you provide number (7) that reproduces the issue? It may be easier for me to debug something I can walk though instead of trying to look at commits because I don't have all the context. Sorry I didn't see the other commit, I just looked at the commit you linked to :(

**Comment by DragonRaider5** [comment]
Hey, strangely enough I'm using the following with success:
```javascript
typeCast (field, next) {
  if (field.type === 'BIT' && field.length === 1) {
    const value = field.buffer()

     if (value === null) {
       return null
     }

     return value[0] === 1
  }

  return next()
}
```

**Note:** If `field.type` is not BIT and `field.length` is not 1, I'm invoking none of the before mentioned functions. However everything still works as expected. Does this have to do with me calling the next "middleware" in this case? I guess the docs could do some additional clarification here (unless I've over looked something).

**Comment by dougwilson** [comment]
Hi everyone (and @DragonRaider5 welcome to this thread). I _finally_ took some time to really bang out the custom type cast documentation to be much more informative (I think, at least) around how to use this. I think it answers the questions in this issue, at least, though.

@DragonRaider5 for your recent question, it should now be answered in the new documentation section: https://github.com/mysqljs/mysql#custom-type-casting

If it doesn't, please let me know what specific questions it still leave open in your mind and I can help improve the documentation directly to help out everyone 🎉
