### ISSUE TITLE
[error handing][err.fatal] do not working

### ISSUE THREAD

**Issue by aqnaruto** [mysqljs/mysql#1997]
here is my code
`
log('submitData方法运行出错：'+err.message+'错误代码是'+err.code+'  err.fatal:'+err.fatal);
`
here is run capture image
![qq 20180413191140](https://user-images.githubusercontent.com/9067159/38731818-7525f6f6-3f4e-11e8-8e61-7af1c3d8d2fb.jpg)

**Comment by aqnaruto** [comment]
it is should be  bool type ,but undefined

**Comment by aqnaruto** [comment]
and is here sombody know how to get the mysql error code such as '1062'

**Comment by dougwilson** [comment]
Hi @aqnaruto you can find both information in our docs at https://github.com/mysqljs/mysql#error-handling

For `err.fatal`:

> If the error is not from a MySQL protocol operation, this properly will not be defined.

Your error above is a query error, not an underlying protocol operation, so it's not defined.

For mysql error code such as '1062': there is an undocumented property `err.errno` you can use. I'll get it documented 👍

**Comment by icepoint0** [comment]
因为你长得太丑了 兄弟

**Comment by aqnaruto** [comment]
@dougwilson ok,thank you , but  i think this is not friendly to developer.  i think the [error handing][err.fatal]  better be giving a infomation instead of be null

**Comment by dougwilson** [comment]
Hi @aqnaruto because many errors can happen, even those objects from Node.js itself, we only set the property on those errors that we produce as fatal errors. If you want to make a pull request with the change you want to see along with README changes that described (a) when it will be true, (b) when it will be false and (c) when it will be undefined, please feel free 👍 I was just stating how it currently works. You're always welcome to make proposals (ideally in the form of a pull request) to alter behavior to how you think would be better.
