### ISSUE TITLE
[DEP0096] DeprecationWarning 

### ISSUE THREAD

**Issue by florenthagard** [mysqljs/mysql#2003]
[DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
on mysql/lib/protocol/Protocol.js:  Timers.unenroll(sequence);

NodeJS 10

**Comment by dougwilson** [comment]
Unless someone knows another way, it's not really fixable in Node.js 10.0. The PR in Node.js https://github.com/nodejs/node/pull/20298 is rolling and so we'll then have a non-deprecated API to use hopefully in some future 10.x release.

**Comment by dougwilson** [comment]
Node.js 10.1 came out but not with the API we need, so we're still waiting for a Node.js release.

**Comment by dougwilson** [comment]
To update this: the needed API has been merged into Node.js 10.x branch now, and so it will be available with Node.js 10.2 I presume. The code still needs to be changed in this module to use the new APIs. I'm going to take a look, but if anyone is inclined to do so, you're also welcome to open a pull request with Node.js 10.x compat 👍

**Comment by coreyfarrell** [comment]
@florenthagard not sure if github would have sent a notice so I'll comment here, I've created a PR that addresses nodejs 10 compatibility.  semver `10.0 | 10.1` will still produce the deprecation warning as the new API is unavailable, the new API will be used by default for `>=10.2`.  Compatibility is accomplished by creating a `setTimeout` and `clearTimeout` ponyfill.  Both directly use the built-in nodejs functions if `.refresh()` is supported, otherwise both are re-implemented based on the deprecated API's.

I also fixed the error on `test/unit/connection/test-connection-ssl-ciphers.js` in nodejs 10.  When I ran the test locally (using nvm on Fedora 28) `RC4-SHA` was not an available cipher so the test failed.

**Comment by pauranik51** [comment]
I facing the same issue.. Please tell me, when can I expect this to be updated??

**Comment by AlexanderProd** [comment]
Same issue here, I'm wondering why the issue was closed.

**Comment by dougwilson** [comment]
The PR was merged, which closed related issues automatically. I was mainly hoping someone would test it out. Would you be willing to test the fix to validate before release? Install instructions in the last section of https://github.com/mysqljs/mysql#install

**Comment by emirpalm** [comment]
@dougwilson run npm console install mysqljs / mysql and correct the problem

**Comment by jediborre** [comment]
Still In Node v10.6.0

(node:25325) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:25325) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

**Comment by dougwilson** [comment]
What version of this module are you using?

**Comment by jediborre** [comment]
v2.15.0

**Comment by dougwilson** [comment]
So 2.15.0 was published before Node.js 10 existed, let alone when this was fixed :) You just need to install the current version of this module to get the Node.js 10 support :+1:

**Comment by jediborre** [comment]
Working  mysql@2.16.0

**Comment by dragonfriend0013** [comment]
I have updated to node v10.8.0 and mysql version 2.16.0 and i am still getting this warning.  any thoughts?

**Comment by dougwilson** [comment]
Open a new issue with full code and steps to reproduce.
