### ISSUE TITLE
Quit inactivity timeout : Lambda / node 8.10

### ISSUE THREAD

**Issue by a1anw2** [mysqljs/mysql#2091]
After looking around, I see this was a bug others have bumped into, but a claim that it was the fault of node 4 and all you needed to do was to upgrade.   This however does not help.

I am running on AWS Lambda with node 8.10 and every so often I get the following in the log files.  It is intermittent with no specific reason.   I am opening a connection and closing it down on a 'finally' clause if that helps.

```
2018-08-21T09:40:45.331Z	46fbd76e-a526-11e8-b235-4de84692bdfc	Unhandled rejection Error: Quit inactivity timeout
at Quit.<anonymous> (/var/task/node_modules/promise-mysql/node_modules/mysql/lib/protocol/Protocol.js:163:17)
at emitNone (events.js:106:13)
at Quit.emit (events.js:208:7)
at Quit._onTimeout (/var/task/node_modules/promise-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:124:8)
at Timer._onTimeout (/var/task/node_modules/promise-mysql/node_modules/mysql/lib/protocol/Timer.js:32:23)
at ontimeout (timers.js:482:11)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5)
--------------------
at Protocol._enqueue (/var/task/node_modules/promise-mysql/node_modules/mysql/lib/protocol/Protocol.js:144:48)
at Protocol.quit (/var/task/node_modules/promise-mysql/node_modules/mysql/lib/protocol/Protocol.js:91:23)
at Connection.end (/var/task/node_modules/promise-mysql/node_modules/mysql/lib/Connection.js:241:18)
at /var/task/node_modules/promise-mysql/lib/helper.js:16:24
at Promise._execute (/var/task/node_modules/bluebird/js/release/debuggability.js:303:9)
at Promise._resolveFromExecutor (/var/task/node_modules/bluebird/js/release/promise.js:483:18)
at new Promise (/var/task/node_modules/bluebird/js/release/promise.js:79:10)
at Connection.promiseCallback (/var/task/node_modules/promise-mysql/lib/helper.js:6:10)
at connection.end (/var/task/node_modules/promise-mysql/lib/connection.js:96:28)
at Object.list [as GET] (/var/task/api/console/solicitation.js:167:14)
at <anonymous>
```

**Comment by j8jacobs** [comment]
I was getting the exact same error with the same environment. I wrapped my end() function in a try catch, sometimes it will fail from the previous lambda function. My function works again and I don't now the ramifications but my function is executing everytime now but here's the code I used to make this work: 
`
const endError = (err) => err ? console.log('End failed with error: ' + err) : console.log('DB connection end successful');
const endConnection = (db) => new Promise(function (resolve, reject) {
  try {
    db.end(endError);
    resolve();
  } catch (err) {
    console.log(`Err:endConnection:${err}`)
    return reject(`Err:endConnection:${err}`);
  }
});
`
now you can await the connection close... like i said though, the print statement sometimes won't show until the next execution though. Would love if someone could let me know what problems this may incur

**Comment by wips** [comment]
I'm having the same issue on AWS Lambda NodeJs8. 
There're also similar bugs reported for older node versions: https://github.com/mysqljs/mysql/issues/1223, https://github.com/mysqljs/mysql/issues/1334.

Does anybody has ideas of how we can debug it on AWS?

**Comment by dougwilson** [comment]
There are two issues, one which was an actual regression in Node.js 4.2.0 we worked around and the seconds Lambda users.

I'm not familiar with lambda or have an account there. If someone who does can offer a fix, that is likely the best way forward. I'm also open to hearing other ways to move this forward as well.

**Comment by wips** [comment]
I've seen somewhere (unfortunately I can't find the link anymore) a suggestion to wait until pool is ended before finishing a lambda. So I made my lambdas wait until `pool.end()`s, before they call `callback`. Previously a lambda just called `pool.end()` w/o waiting for the result.

I haven't seen the issue since the code was deployed yesterday on a dev environment. We're having prod deployment today. I'll give it few days to work on prod to see whether error repeats. I'll post results here then.

**Comment by a1anw2** [comment]
Just to be clear here @wips there is no connection pooling going on here with my issue.

**Comment by wips** [comment]
@a1anw2, do you use a single connection?

@dougwilson, it has been 3 days since I deployed [the fix](https://github.com/mysqljs/mysql/issues/2091#issuecomment-417616109). No errors have been seen since then. It looks like it worked for me.

**Comment by dougwilson** [comment]
The end method is not blocking, as there is no blocking network APIs in Node.js that would allow .end to be blocking. Docs on end are here if it helps: https://github.com/mysqljs/mysql/blob/master/Readme.md#terminating-connections

**Comment by a1anw2** [comment]
Thanks @dougwilson .  

Looks like `.destroy()` is probably worth calling instead of `.end()` as I re-read this in the cold light of day.

**Comment by wips** [comment]
@a1anw2, as @dougwilson said `.end()` is non-blocking, but this may lead your code to the same issue that was in mine - I was just calling `.end()` w/o waiting the operation to actually complete.

To actually wait for the connection end you can't just `await dbConn.end()`, because `.end()` doesn't return a promise. What you need is to create a promise and return it. Smth like the following:

```js
return new Promise((resolve, reject) => {
    dbConn.end(error => error ? reject(error) : resolve());
});
```
Btw, the same thing is with `await dbConn.query(sqlStat.sql, sqlStat.params)` from your code snippet - `.query()` doesn't return a promise, so there's no point in `await`-ing it.

**Comment by a1anw2** [comment]
I didn't include the require modules ... i am using https://www.npmjs.com/package/promise-mysql that wraps all the calls in a promise.

**Comment by douglasdouglasdouglas** [comment]
I'm on AWS Lambda with Node 8.10 and I've randomly been having this error, but prompted by @wips I did some experimenting, and I _think_ I solved the issue simply by including a function(err){...} in .end(). Like:

`connection.end(function(err) {console.log("Database connection end error is " + err )}); `

It seems that simply handling the error in that way is all the was needed- otherwise, my Lambda function would randomly crash no matter how I tried to `catch` the error. With this statement included, the queries run fine, _even if_ I also pass in `{timeout : 1}`, which by itself consistently causes the error to appear.

**Comment by dougwilson** [comment]
So pretty much, as far as I can tell, the answer for lambda is to either (a) don't finish your function until the callback of `conn.end(cb)` is called or just `conn.destroy()` to forcefully kill the connection at the end of your function.

**Comment by adia-alderson** [comment]
So for anyone who runs into this issue, later on, I think I may have figured it out?

So a few things I noticed. The setTimout timer for conn.end is never cleared. So as long as the lambda is warm the timer is still going as apparently lambda doesn't clear its execution context unless the lambda is destroyed/not warm. So when that lambda is reused if X amount of seconds (30 is the default or whatever you passed into the timeout option for conn.end) has passed since that lambda has been hit, when it is reused it emits that error first THEN starts executing your handler code.

This article explains it better (number 19 in particular):
https://medium.com/radient-tech-blog/aws-lambda-and-the-node-js-event-loop-864e48fba49

The amazon documentation states:
https://docs.aws.amazon.com/lambda/latest/dg/running-lambda-code.html
"Background processes or callbacks initiated by your Lambda function that did not complete when the function ended resume if AWS Lambda chooses to reuse the execution context. You should make sure any background processes or callbacks in your code are complete before the code exits."

Since the lambda function exited before the callback for setTimeout was called I'm guessing it resumes once that same lambda is executed again if it decided to reuse the execution context.

Hopefully, this helps? I'm currently trying to figure out the best solution for this as how long lambda's stay alive varies.......

**Comment by jacobhobson** [comment]
```connection.end(function(err) {return;});```

Running the above for my connection.end() calls caused Lambda to not care that it didn't receive a handshake from the last run in the previous Lambda call. Essentially, need to write a promisify for the end() method, but I haven't done it yet.

**Comment by elminson** [comment]
> @a1anw2, as @dougwilson said `.end()` is non-blocking, but this may lead your code to the same issue that was in mine - I was just calling `.end()` w/o waiting the operation to actually complete.
> 
> To actually wait for the connection end you can't just `await dbConn.end()`, because `.end()` doesn't return a promise. What you need is to create a promise and return it. Smth like the following:
> 
> ```js
> return new Promise((resolve, reject) => {
>     dbConn.end(error => error ? reject(error) : resolve());
> });
> ```
> 
> Btw, the same thing is with `await dbConn.query(sqlStat.sql, sqlStat.params)` from your code snippet - `.query()` doesn't return a promise, so there's no point in `await`-ing it.

This solve my problem, Thanks

**Comment by a1anw2** [comment]
Thanks @elminson .  I am/was using the promise-mysql library, so that does all the promise'ing for you.

**Comment by nkemcels** [comment]
Had this same issue because I was working with a slow internet connection. So it frequently timed out. Increasing the timeout value worked for me. 

```js
...
const mysql = require('mysql');

mysql.createConnection({
        host: dbParams.HOST,
        user: dbParams.USER,
        password: dbParams.PASSWORD,
        database: dbParams.DATABASE,
        timeout: 600000,
        ssl: {
          rejectUnauthorized: false,
        },
});
...
```

**Comment by Aijaz12550** [comment]
I was facing the same issue in aws lambda. destroying the connection works for me.

![image](https://user-images.githubusercontent.com/42912599/111899024-901e0980-8a4b-11eb-85df-b6862fe7fc2c.png)
