### ISSUE TITLE
the big number update problem?

### ISSUE THREAD

**Issue by yqsailor** [mysqljs/mysql#2188]
I want set database field of decimal(36,16) to increase 1000000.00000000011, but nodejs not support this number,

I set the  update sql to `UPDATE tableName set amount = amount + '1000000.00000000011'`, but the result is wrong. 

Then i set the update sql to `UPDATE tableName set amount = amount + CAST('1000000.00000000011' AS DECIMAL(32, 16))` that resolved my problem.

Is there some other method to solve this problem?

**Comment by dougwilson** [comment]
Hi @yqsailor , I think this is because the SQL you are showing above:
```sql
UPDATE tableName set amount = amount + '1000000.00000000011'
```

Is adding a number to a string, in which case MySQL will perform an automatic CAST on the string to a number prior to performing the add operation. The second SQL where you perform an explicit cast bypasses the rules for the MySQL implicit cast.

You can read more about how implicit casting works in MySQL in the MySQL manual: https://dev.mysql.com/doc/refman/5.5/en/type-conversion.html

For string -> number conversations, MySQL will convert the string to a FLOAT, which looses the precision of your large number. By you doing the explicit cast, that makes MySQL perform the addition correctly.
