### ISSUE TITLE
When are custom typecasts used?

### ISSUE THREAD

**Issue by FabianTe** [mysqljs/mysql#2203]
Hi,

when using a custom type cast, when is it being used? Only on `SELECT`s?

I would think that it is also being used on `UPDATE`, `INSERT` and `DELETE` but it does not seem like it.

**Comment by dougwilson** [comment]
Hi @FabianTe yes, the type cast functionality "will cast mysql types into native JavaScript types". There is no functionality in this module to case JavaScript types back into MySQL types outside what is described in the rules here: https://github.com/mysqljs/mysql#escaping-query-values

If you'd like to see some changed / new functionality, you're welcome to make a pull request with the idea. Otherwise, if you can describe what you'd like to see in detail here, perhaps someone will be able to pick it up and make the pull request.

**Comment by FabianTe** [comment]
Thanks for your reply.

Well, I would like to be able to customize not only how data will be parsed into JS types when reading data, but also when inserting, updating and maybe even deleting, when they are performed with query placeholders like here:

```
connection.query('SELECT * FROM `books` WHERE `author` = ?', ['David'], function (error, results, fields) {
  // error will be an Error if one occurred during the query
  // results will contain the results of the query
  // fields will contain information about the returned results fields (if any)
});
```

The reason I want this is because I noticed that `BIT` columns are returned as `Buffer` objects, which I only use as boolean values. Therefore I parse them into the JavaScript `boolean`. This works when selecting. And sadly this is a bad example because writing `true` or `false` into a `BIT` column is allowed with MariaDB, writing, updating and deleting also works fine in this case. But with other column types it may not!

That's why I'd like to be able to set a `sql2js` and a `js2sql` cast, which may be two separate functions. Right now I implement this in my own service layer which is fine, but I figure it would be nice to have this in this package.

**Comment by dougwilson** [comment]
Gotcha. So you should be able to use the custom formatting function (https://github.com/mysqljs/mysql#custom-format) in order to encode your js to sql value transformations.

**Comment by FabianTe** [comment]
Thanks, that might work!
