### ISSUE TITLE
pool getConnection doesn`t work

### ISSUE THREAD

**Issue by forenheith** [mysqljs/mysql#2207]
Hi all, I have the issue with getConnetion() method.I just take the code from the example in the documentation, pass my credentials and nothing works. No errors, no callback calls, no connection returned, nothing at all. Here is my code:
https://pastebin.com/U4K6sszM
Any ideas? How can I debug this issue? Thanks.

**Comment by forenheith** [comment]
Even if I pass  mysql.createPool({}); I have no error. Behavior is completely the same.

**Comment by dougwilson** [comment]
Hi @forenheith sorry you are having issues. I see the code you posed, but the `getFreeConnection` does not seem to return anything even if a connection is opened. Could you show an example of how you would call the `getFreeConnection` function?

**Comment by forenheith** [comment]
@dougwilson thank for your answer and sorry for my not totally workable example. I can't edit it so I've created a new one https://pastebin.com/sJmjNEUk

**Comment by dougwilson** [comment]
Thank you @forenheith . 

So the issue is that in Node.js, you cannot use `return` within a callback. This is because async callbacks provide no way to return a value. Instead, you need to have your function take a callback function, and once the callback completes, pass that as an argument to the callback as well. Here is an example:

``js
let mysqlConnection = getFreeConnection();

function getFreeConnection(callback) {
    pool = getConnectionsPool();
    try {
        pool.getConnection(function cb(err, connection) {
 
            if (err) {
                console.error(`error getting connection from pool; ${err}`);
                callback(err);
                return;
            }
 
            if (!connection) {
                console.error(`error getting connection from pool`);
                callback(null);
                return;
            }
            callback(null, connection);
        });
    } catch (e) {
        console.error(e);
        callback(e);
    }
}
 
function getConnectionsPool() {
    pool = pool ?
        pool :
        mysql.createPool({
            host: process.env.MYSQL_HOST,
            user: process.env.MYSQL_USER,
            password: process.env.MYSQL_PASSWORD,
            database: process.env.MYSQL_DB
        });
 
    if (!pool) {
        console.error(`error getting connections pool`);
        return null;
    }
    return pool;
}
```

You would then use the function like the following:
```js
getFreeConnection(function (err, connection) {
  if (err) {
    console.error(`had an error: ${err}`);
  } else if (!connection) {
    console.error('cannot get connection');
  } else {
    console.log(`got connection: ${connection}`)
  }
});
```

I hope that helps. Node.js provide some information about the callback pattern as well: https://nodejs.org/en/knowledge/getting-started/control-flow/what-are-callbacks/
