### ISSUE TITLE
util.js ERR_INVALID_ARG_TYPE('superCtor.prototype'

### ISSUE THREAD

**Issue by skidvd** [mysqljs/mysql#2209]
I am simply trying to establish a connection pool as per the docs, but I receive the following error:

```
util.js:310
    throw new ERR_INVALID_ARG_TYPE('superCtor.prototype',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type Function. Received type undefined
    at Object.inherits (util.js:310:11)
```

relevant code excerpts:
```
const mysql = require('mysql');
const config = require('./config');
const pool  = mysql.createPool({
    connectionLimit : config.dbconnectionLimit,
    host            : config.dbhost,
    port            : config.dbport,
    user            : config.dbpassword,
    password        : config.dbpassword,
    database        : config.dbname
});
let response;

// ....

try {
        pool.getConnection(function(err, connection) {
            if (err) throw err; // not connected!

            // Use the connection
} catch (err) {
        console.log(err);
        return err;
}
```

This is happening with mysql 2.17.1 being running on a node 8.10 env.

**Comment by dougwilson** [comment]
Thank you for the report. I'm not able to reproduce the error with the given code above and versions. I did have to replace `require('./config');` with `{};` since you didn't provide that file, so perhaps that is the difference why. Really, the stack trace should be longer than what you posted and point to the location in which `util. inherits` was called to create the error.

Any additional details you can provide or a pull request with a fix would be most welcome.

**Comment by skidvd** [comment]
My apologies.  This error has turned out to be a problem on my end.  Long story short, some rather complex environmental configurations resulted in this unexpectedly being invoked with the incorrect node version.
