### ISSUE TITLE
Differences with ProxySQL connection pooling?

### ISSUE THREAD

**Issue by chainhead** [mysqljs/mysql#2247]
I am keen to know how is connection pooling in `mysql` package different from the one offered by ProxySQL [Connection Pooling](https://github.com/sysown/proxysql/wiki/Detail-Answer's-On-FAQ#question-1--connection-pooling-in-proxysql).

Under what circumstances should either (`mysql` or `proxysql`) be chosen?

**Comment by dougwilson** [comment]
I'm not familiar with proxysql so not really sure on the answer especially to compare. I can help answer and specific questions how this module, though.

**Comment by chainhead** [comment]
@dougwilson You can read all about ProxySQL [here](https://proxysql.com/). Specifically on connection pooling, [here](https://github.com/sysown/proxysql/wiki/Detail-Answer's-On-FAQ#question-1--connection-pooling-in-proxysql).

**Comment by dougwilson** [comment]
Thanks, but I have a lot of other things to do besides learn how ProxySQL works to then come up with a comparison between the pooling mechanisms :) If you can ask specific questions I can answer about this module, I'm happy to help, otherwise, it may be a better question to ask on a site like StackOverflow.
