### ISSUE TITLE
Question: Best Practice for testing connection on creation

### ISSUE THREAD

**Issue by jazzerscott** [mysqljs/mysql#2261]
Hello, 

I've searched the issues and documentation and am not sure on the best way to test a connection when creating for a pool.  Specifically we had a scenario after a db failover there was a delay in the dns getting updating to point to the new master db, and as a result we got connected the old master db which was now in  read-only mode.  On connection creation I want to test to make sure it is not connected to a read-only database and close the connection if is.  I see that pool has this event:
```js
pool.on('connection', function (connection) {
  connection.query('SET SESSION auto_increment_increment=1')
});
```
But I'm sure if there would be any consequences of making a call to mysql to check if in read only mode during this event.  Would using this connection to make a test query impact whatever is about to use this connection for something else?

Thanks
Scott

**Comment by dougwilson** [comment]
Hi @jazzerscott , there isn't a current solution in this module for the particular issue you described. This is because even if we introduced a method to test if the connection was "valid", the only recourse this module would have to get a "valid" one would be to create a new connection, but in your situation that can still end up getting with the old DNS and be invalid, creating a small loop.

I would suggest to perhaps use a more flushed-out pool module to get more flexibility in how you want your system to act in your situation (https://www.npmjs.com/package/generic-pool) but even that module doesn't easily support what you want. It does allow you to validate a connection, but just like this module, validation is just on existing connections, not the new connections still using stale DNS.

So really your best bet would be able to control the creation of the connection itself, which at that point using https://www.npmjs.com/package/generic-pool would be the method to do so, as it would be completely custom logic. You could define your creation method to call `mysql.createConnection` and then check if it is read-only and then implement some kind of back-off mechanism to prevent a sudden influx of connection creation during your DNS flip over.
