### ISSUE TITLE
Query SELECT with IN operator not working

### ISSUE THREAD

**Issue by darrylsepeda** [mysqljs/mysql#2266]
Hi, I have a question, I can't remember if this query is working before or not, but the same query works fine if I tried to run it in phpmyadmin.

```
SELECT a.*, b.status FROM tableA a LEFT JOIN tableB b ON a.id=b.id WHERE a.id IN (?)
```

and I added parameter `1,2,3` to replace `?` (question mark in the query) so it becomes:

```
SELECT a.*, b.status FROM tableA a LEFT JOIN tableB b ON a.id=b.id WHERE a.id IN (1,2,3)
```

This query works fine in phpmyadmin, can return exactly data with id 1, 2, and 3, but when I run it using npm mysql, it doesn't work as expected, in some cases it returns empty row, and in another cases, only return data with the first id of the sequence (1).

Does anybody gone through the same issue?
I'll appreciate any help.

**Comment by darrylsepeda** [comment]
I just found the answer, after trying to debug the compiled query, I found that the result has quotes on input (I guess because of PDO). So it becomes like this:

```
SELECT a.*, b.status FROM tableA a LEFT JOIN tableB b ON a.id=b.id WHERE a.id IN ('1,2,3')
```
instead of 
```
SELECT a.*, b.status FROM tableA a LEFT JOIN tableB b ON a.id=b.id WHERE a.id IN (1,2,3)
```

as an alternative, I didn't use param, directly use variable on the query (not sure if this is a good approach, but at least it works for now):

```
connection.query(`SELECT a.*, b.status FROM tableA a LEFT JOIN tableB b ON a.id=b.id WHERE a.id IN (${id})`, callback)
```

**Comment by dougwilson** [comment]
Yea, in order to get `SELECT a.*, b.status FROM tableA a LEFT JOIN tableB b ON a.id=b.id WHERE a.id IN (?)` to expand as you expect, you need to provide an actual array of the numbers to this module (as in `[1,2,3]`. The output you are getting would be produced when you're instead providing a single string of `'1,2,3'` to this module.

The rules for how values are expanded into `?` are defined here: https://github.com/mysqljs/mysql#escaping-query-values
