### ISSUE TITLE
Information about CVE-2019-14939?

### ISSUE THREAD

**Issue by carnil** [mysqljs/mysql#2267]
Hi

Recently a CVE (CVE-2019-14939) was associated with the issue https://github.com/mysqljs/mysql/issues/2257, cf. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14939 . Is there any further informations/details for downstreams shipping the nodejs module? Debian is for instance shipping  2.16.0-1 in buster.

Regards,
Salvatore

**Comment by dougwilson** [comment]
Hi @carnil thanks for the report. The issue is being worked on and a fix will arrive within the timeline agreed upon with the initial reporter. I'm unaware of how a CVE has been detailed before the embargo / fix has been made available, though.

**Comment by dougwilson** [comment]
Since it's still being worked on and has yet to be released, if you would like to be included in the discussions / details, you're welcome to email me (https://github.com/mysqljs/mysql#security-issues is our security reporting procedure and my email is https://github.com/mysqljs/mysql/blob/master/package.json#L10) and I can loop you in on what the details are and the plan for the fix is.
