### ISSUE TITLE
 Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by vDomas777** [mysqljs/mysql#2316]
Hello, when i use query after 5 min i get this error (in title)
https://pastebin.com/dBBqEaCA

**Comment by FilipGrebowski** [comment]
Try using a connection pool.

**Comment by akleiber** [comment]
a pool will not help here - I am pretty sure this is due to `wait_timeout` / `interactive_wait_timeout` and the server closes the connection after that timeout.
@vDomas777 check your global timeouts on the database:

```
SELECT @@global.wait_timeout, @@session.wait_timeout, @@global.interactive_timeout, @@session.interactive_timeout
```

The only real option is to close connections in the pool after some idle time. 
Or you handle it in your code, i.e. catch errors and retry the query.

**Comment by dougwilson** [comment]
Well, yes and no.

Yes, even when using the pool you will get connections closed due to idle timeout, but no, using it does not mean you have to handle it. One of the benefits to using the pool is that it will handle connections closed due to idle limits on the server automatically, without needing your code to handle it specifically.

The example provided is just opening a single connection and trying to hang on to it indefinitely, which is why OP has the issue. Any network hiccup will cause OP's program to break, so either using a pool or opening / closing connections are the way to go in the long run.

**Comment by PLQin** [comment]
So, how to deal with this error ： 
```
Error: Connection lost: The server closed the connection
```

**Comment by Julianvschijndel** [comment]
I also have this error. How can this be solved?
