### ISSUE TITLE
@wangfengyuan double check that `multipleStatements` config option is actually set

### ISSUE THREAD

**Issue by wangfengyuan** [mysqljs/mysql#2328]
@wangfengyuan double check that `multipleStatements` config option is actually set

_Originally posted by @sidorares in https://github.com/mysqljs/mysql/issues/1545#issuecomment-606592564_

my test demo just like this
```js
var mysql = require('mysql')

var myCon = {
    host: 'xxx',
    port: '3306', // 端口号
    database: 'admin', // 数据库名
    user: 'xxx', // 数据库用户名
    password: 'xxx', // 数据库密码
    multipleStatements: true
    
}
var connection = mysql.createConnection(myCon)
connection.connect()

connection.query('SELECT 1; SELECT 2;', function (error, results, fields) {
    if (error) throw error;
    // `results` is an array with one element for every statement in the query:
    console.log(results[0]); // [{1: 1}]
    console.log(results[1]); // [{2: 2}]
});

connection.end()
```

but I get the error: 
```
Error: ER_PARSE_ERROR: Proxy ERROR:You have an error in your SQL syntax; check the manual that corresponds to your Mysql server version for the right syntax to use near 'SELECT 2 ' at line 1
```
it seems that multipleStatements has not take effect,
Is there something wrong with my code ？

**Comment by dougwilson** [comment]
Why is there a `Proxy ERROR` inside your error message? That is not typical from a MySQL server. Are you connecting to some kind of proxy? If so, it is likely that proxy either doesn't support multiple statements or is not passing that request along to the underlying MySQL server.

Unfortunately if I take your code as-is and connect to my own MySQL server it works without an issue, so if the above does not help, we'd need to know enough information about your set up in order to replicate your issue.

**Comment by wangfengyuan** [comment]
Which proxy settings will affect this？I didn't do extra special settings

**Comment by dougwilson** [comment]
That, I do not know. Unfortunately if I take your code as-is and connect to my own MySQL server it works without an issue, so if the above does not help, we'd need to know enough information about your set up in order to replicate your issue.
