### ISSUE TITLE
Custom query format adding extra quotes to the escaped values

### ISSUE THREAD

**Issue by vtolenti89** [mysqljs/mysql#2349]
The following custom query format is adding extra quotes to the final query, thus throwing an error when it is executed:

**Problem**
```
// Custom Query
connection.config.queryFormat = function (query, values) {
  if (!values) return query;
  return query.replace(/\:(\w+)/g, function (txt, key) {
    if (values.hasOwnProperty(key)) {
      return this.escape(values[key]);
    }
    return txt;
  }.bind(this));
};
```

Consider the following code:
```
let sql = 'SELECT * FROM posts ORDER BY :sort;';
const values = {sort: 'DESC'};
connection.query(sql, values);
```

Where the final query is  
```
SELECT * FROM posts ORDER BY 'DESC';
```

The single quotes around DESC throws an error and it should not be there. Is there any way of getting rid of it when escaping characters.

Thanks in advance.

**Comment by dougwilson** [comment]
This is because the custom query you are using replaces `:foo` with a SQL value, but you are trying to use raw SQL there as `DESC` is not a SQL value, but rather part of the SQL syntax itself. You can pass in a `mysql.raw` value to keep it unquoted, raw SQL:
```js
let sql = 'SELECT * FROM posts ORDER BY :sort;';
const values = {sort: mysql.raw('DESC')};
connection.query(sql, values);
```

**Comment by vtolenti89** [comment]
Thank you @dougwilson. It is working now.

**Comment by redixhumayun** [comment]
Does`mysql.raw` also prevent SQL injection attacks? Or would I now need to write something like `mysql.escape(mysql.raw(value))`?

**Comment by dougwilson** [comment]
Hi @redixhumayun the purpose of `mysql.raw` is that prevention of SQL injection is now in your hands and not in the hands of this module. If you want this module to assist you, you'll need to use the facilities like placeholders and `mysql.escape`. If the `value` you are passing to `mysql.raw` needs to be escaped, there is no purpose to using `mysql.raw`.

I'm just locking this as resolved as the issue is closed and resolved from the original creator. Always best to open a new issue and provide a link to an old issue if you believe it is still relevant.
