### ISSUE TITLE
insertId returns 0 when field is GUID

### ISSUE THREAD

**Issue by dlednik** [mysqljs/mysql#2367]
How do I get the guid back of inserted line when the table generates GUIDs and store them in binary format?

Take this table for example:
```
CREATE TABLE `properties` (
  `guid` binary(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID())),
  `description` text NOT NULL,
  PRIMARY KEY (`guid`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

is this even supported?

**Comment by dougwilson** [comment]
Hi unfortunately this is a limitation of the MySQL protocol -- the insertId can only be an integer (see protocol definition https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html), so when you define your primary key to be a different type, it will always come back as zero. Even if you try and use `SELECT LAST_INSERT_ID()` (https://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_last-insert-id) it won't work because it also only returns an integer.

**Comment by dlednik** [comment]
ok, so just need to do this first
```
SELECT UUID() as guid;
```
And then insert the line with generated guid.
