### ISSUE TITLE
[Question] Does this drive support mysql version 4.x?

### ISSUE THREAD

**Issue by thanhlq** [mysqljs/mysql#2395]
Mysql company is using a very old mysql version 4.x so I don't know if this drive support?

Thanks very much your answer.

**Comment by dougwilson** [comment]
Hello, sorry no one got back to your question. Yes, this module should support 4.x versions of MySQL, but there is no on going testing around it, due to the lack of support on the CI. If you find it not working, you are welcome to contribute fixes around it, as this module doesn't specifically not support it.
