### ISSUE TITLE
The module rounds big numbers automatically?

### ISSUE THREAD

**Issue by DualByte** [mysqljs/mysql#2400]
When I do a query and get the exact thing I want. The value is 701175644318597181 in the database but the module gives me 701175644318597100. I am not modifying the results in anyway but it still gives back the wrong result?

**Comment by dougwilson** [comment]
This is just the nature of JavaScript itself... it cannot actually represent a number that large. You can try this out in the Node.js command line:
```
$ node
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> num=701175644318597181
701175644318597100
> num
701175644318597100
>
(To exit, press ^C again or ^D or type .exit)
>
```

Because of this, we provide a method to get your big numbers as a string. You can find the different big number options listed in the connection configuration documentation here: https://github.com/mysqljs/mysql#connection-options

> supportBigNumbers: When dealing with big numbers (BIGINT and DECIMAL columns) in the database, you should enable this option (Default: false).
> bigNumberStrings: Enabling both supportBigNumbers and bigNumberStrings forces big numbers (BIGINT and DECIMAL columns) to be always returned as JavaScript String objects (Default: false). Enabling supportBigNumbers but leaving bigNumberStrings disabled will return big numbers as String objects only when they cannot be accurately represented with [JavaScript Number objects] (http://ecma262-5.com/ELS5_HTML.htm#Section_8.5) (which happens when they exceed the [-2^53, +2^53] range), otherwise they will be returned as Number objects. This option is ignored if supportBigNumbers is disabled.
