### ISSUE TITLE
Should return a better error when attempting to insert NaN into numeric field?

### ISSUE THREAD

**Issue by ericman314** [mysqljs/mysql#2403]
There have been a few issues raised related to accidentally trying to insert a `NaN` into a numeric field.

For example, a statement such as:

```js
db.query('SELECT * FROM customers WHERE id = ?', [0 / 0])
```

is sent to the db as `SELECT * FROM customers WHERE id = NaN`, which results in the error:

```
Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
```

This error message has led to a bit of confusion in the past (see #1716, #1880, and #2158). Since mysql cannot store NaN and Infinity values at all, perhaps the behavior could be improved by refusing to perform the query at all, and returning an error message such as, `Error: Attempting to insert NaN into numeric field`. Or at the very least, the NaN should be quoted so that it is interpreted as a string rather than an object name.

This also brings up the question--and unfortunately I don't have time to test this right now--what happens if "NaN" or "Infinity", are the names of actual objects in the database? Could this lead to unexpected (or worse, malicious) behavior?

**Comment by dougwilson** [comment]
You are correct in that this has been discussed several times before, and even then, nothing has changed in our contract:

1. We are very explicit on this fact in our docs (https://github.com/mysqljs/mysql#escaping-query-values): "NaN / Infinity are left as-is. MySQL does not support these, and trying to insert them as values will trigger MySQL errors until they implement support." so there is no surprise that this is the behavior.
2. When using our `?` behavior, you can never pass in a value that will throw an error by design -- introducing a throw will be a huge change, with enormous amounts of code out there not wrapping in a `try` or similar because it's not possible for an error to be thrown from that.

> Could this lead to unexpected (or worse, malicious) behavior?

This has been brought up before but nothing has ever been produced around this, though. If you think there is something, you are putting all users at risk without even attempting to go through the process of https://github.com/mysqljs/mysql#security-issues
