### ISSUE TITLE
localhost option is being converted to 127.0.0.1 and I can not connect to database.

### ISSUE THREAD

**Issue by arthas009** [mysqljs/mysql#2407]
as described here https://stackoverflow.com/questions/63862985/cpanel-mariadb-connection-fails-with-node-js-mysql-connector/

I am having Error: connect ECONNREFUSED 127.0.0.1:3306.

I can not use localhost option, it's being converted to 127.0.0.1 instead, according the error logs.
In my host, 127.0.0.1 is not being used for mariadb and the only way to connect DB is localhost option. There is also no socket path provided. 

I can connect same database on same host using PHP.

Can anyone suggest a solution ? Why it is converting localhost option to 127.0.0.1 ?

**Comment by dougwilson** [comment]
Hi @arthas009 to make a TCP/IP connection, it can only be done using IPs, not domain names. So in order to connect over TCP/IP, the name provided to this module ("localhost" in your case) is converted to an IP address automatically by Node.js (not this module). The error message you are seeing is coming from Node.js itself. You should see the same message when running the following Node.js code:
```
$ node -e 'require("net").connect(3306, "localhost")'
```

The error you are getting is that the connection was refused to your Node.js app on the TCP port 3306. You can read more about the error messages from Node.js here: https://nodejs.org/dist/latest-v12.x/docs/api/errors.html#errors_common_system_errors

> ECONNREFUSED (Connection refused): No connection could be made because the target machine actively refused it. This usually results from trying to connect to a service that is inactive on the foreign host.
