### ISSUE TITLE
Bug with sql.query

### ISSUE THREAD

**Issue by RayMa78** [mysqljs/mysql#2435]
Hello! i faced a bug when i was using mysql package with discord js ! 
users in discord has ids which length is about 17 - 19 ints 
the problem is > when i try to insert the id to mysql server its working well see blow 
```
id of member -> 771709316411162656
id which shows in mysql database -> 771709316411162656
```
until now all is ok but when i try to select that id from mysql database 
it gives me this results 
```
id -> 771709316411162000
the id shown in database -> 771709316411162656
```
the last three numbers turns to zero for no reason

**Comment by dougwilson** [comment]
Hello! It looks like you are dealing with a MySQL field that is likely a `BIGINT` or `DECIMAL`. JavaScript numbers just cannot hold such a high value (you can see this happening by simply writing `console.log(771709316411162656)` in JavaScript and seeing the output).

In order to work with large numbers, this module provides a few connections options (https://github.com/mysqljs/mysql#connection-options) like `supportBigNumbers` and `bigNumberStrings`. Please check out these options to see what combination you like the best.
