### ISSUE TITLE
Query running in the workbench being much faster than in nodejs

### ISSUE THREAD

**Issue by victorgsp** [mysqljs/mysql#2436]
I'm running the **same query** (in the **same database**) on nodejs and mysql workbench and the execution time is absurdly different. 
Follows the execution duration data.
**nodejs** 22468.275ms (22,5 seconds)
**mysql workbench**: duration 0,019 sec / fetch 0,147 sec

db.config
`{
  "connectionLimit" : 10,
  "host"            : "localhost",
  "user"            : "root",
  "password"        : "root",
  "database"        : "db"
}`

what is the reason for this difference?

**Comment by dougwilson** [comment]
Hi @victorgsp ! That is very strange. I just tried a few different queries between the two and they were both within a few ms of each other (likely network variance). Can you provide the details so we can reproduce this difference and investigate it?

**Comment by victorgsp** [comment]
other information: 
- the mysql is running within a docker
- the main table of query has 9.500.000 records
- has a join with another large table with 1.500.000 records
- the query results are 150000 records

**Comment by dougwilson** [comment]
Thank you. I meant enough information to be able to reproduce the difference; perhaps the table contents, query to run, etc. To determine why it is slow, we need to be able to attach a debugger or other tools to see where the time is being spent during the query.

**Comment by ilanguis** [comment]
same problem too..

**Comment by philfontaine** [comment]
The difference you see in workbench is because workbench adds an implicit `LIMIT X` to your query, and by default that limit is 100. This is why your query is extremely faster in workbench.

![image](https://user-images.githubusercontent.com/16233697/115597175-fbefce00-a2a6-11eb-9280-324a42047cfb.png)

**Comment by Siddharthosatwal** [comment]
Facing the same issue Mysql query on workbench takes 'x' amount of time whereas in the Node JS server it's taking a '2x' amount of time. Need to know how we can reduce this as it will make a lot of difference in the performance.

**Comment by dougwilson** [comment]
Hi @Siddharthosatwal sorry this issue was left open. I was able to verify the answer is what @philfontaine posted above; by default the MySQL workbench adds a `LIMIT` to your query, limiting the number of results. You can go to your settings to remove the limit to test the speed of the entire query results or you can add the `LIMIT` command to your query on this module if you don't want all the results like you get in the workbench.

**Comment by Siddharthosatwal** [comment]
> Hi @Siddharthosatwal sorry this issue was left open. I was able to verify the answer is what @philfontaine posted above; by default the MySQL workbench adds a `LIMIT` to your query, limiting the number of results. You can go to your settings to remove the limit to test the speed of the entire query results or you can add the `LIMIT` command to your query on this module if you don't want all the results like you get in the workbench.

@dougwilson I have remove the limit from the MySQL workbench then today I see the same issue. Can you help in how can we reduce this time.

**Comment by dougwilson** [comment]
Hi @Siddharthosatwal sorry you are still having an issue. Unfortunately you have not provided anything about your environment, your query, your data, or any other type of information in which I could assist in diagnosing your issue. Please open a new issue about your problem and include all relevant information such that I can reproduce the issue and assist in diagnosis.
