### ISSUE TITLE
Example of select statements which query using date time?

### ISSUE THREAD

**Issue by imuno** [mysqljs/mysql#2446]
Hello! I am attempting to query my database by date time to find records from the last week. I have been unsuccessful thus far (something which I think has to do with the fact that time stamps return as a string). If you have the time, I would be very grateful if you could help me understand how to perform such a query. Thank you in advance!

**Comment by imuno** [comment]
For greater context, the query I am trying to perform is:

SELECT CONVERT_TZ(updated_at, '+00:00','-7:00') AS date, count(basket_id)
FROM orders
WHERE state = 'charged'
AND DATE(CONVERT_TZ(updated_at, '+00:00','-7:00')) = DATE(CONVERT_TZ(NOW(), '+00:00','-7:00'))
GROUP BY HOUR(date);

**Comment by williamd5** [comment]
What's the issue here? What does your server respond to this command? If you are looking to convert a `datetime` timestamp obtained as a string in Node, you can use `new Date(yourString)`.

On a side note, make sure the time zones you are using do not have *daylight saving* adjustments. Thus this hardcoded offset of 7 might become invalid. I have no idea whether this is standard practice, but I always store dates and times in UTC in my database. On MariaDB and MySQL you can usually use the UTC_TIMESTAMP() function to get the current UTC time (useful for default value, etc.)

Furthermore, you say you are trying to select records that are no older than 7 days, where in reality it seems your code is attempting to select rows where `updated_at` is the same as `NOW()`. To address that, consider taking a look at this [Stackoverflow thread](https://stackoverflow.com/q/6089960/7089726).

**Comment by dougwilson** [comment]
Closing since there is no further follow up from OP.
