### ISSUE TITLE
How can I write the reconnection code?

### ISSUE THREAD

**Issue by ilkcantnriverdi** [mysqljs/mysql#2483]
Hello, when the connection is lost, I want to reconnect instead of closing the program. When I run this code I get this error. How can I write the reconnection code?

**Comment by dougwilson** [comment]
Once your connection is broken, you just create a new one to replace it. This module provides the createConnection method to create new connections to your Mysql server.

Depending on your application, it may be easier and more advantageous to use a connection pool instead of trying to write your own connection management code.

**Comment by ilkcantnriverdi** [comment]
Thank you for your interest. I am already using creatPool. My problem is that when the connection with the server is lost, the program closes and does not wait to connect again.I have to solve this problem.
