### ISSUE TITLE
Unable to insert timestamps in UTC

### ISSUE THREAD

**Issue by damacster** [mysqljs/mysql#620]
i am setting the timezone connection option to Z (also tried '+00:00'), but the timestamps i insert always get inserted as local time:

``` javascript
mysql.createConnection( 
{host : "localhost", 
 user : xxx,
 password : xxx, 
 timezone : "Z"});
```

my understanding of timezone option is that it is expected to work similar to how `set time_zone = '+00:00';` works in mysql.

if i explicity call `connection.query( "set time_zone = '+00:00'" )` before any of my inserts, it works as expected.

i'm using the latest alpha release (2.0.0-alpha9).

**Comment by techniq** [comment]
:+1:

**Comment by techniq** [comment]
It would be helpful to note in the docs as well that `new Date(0)` (i.e. `1970-01-01 00:00.000Z`) is illegal to insert into a MySQL timestamp column and will throw the following (confusing) error:

`Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '1970-01-01 00:00:00.000' for column 'updated_at' at row 1`

This is because the the date must be at least 1 second into 1970 (i.e. `new Date(1000)`).

[Per the docs](https://dev.mysql.com/doc/refman/5.0/en/datetime.html):
> The TIMESTAMP data type is used for values that contain both date and time parts. TIMESTAMP has a range of '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07' UTC.

Spent a good bit of time today fiddling with node-mysql's `timezone: 'Z'`option and MySQL's `set time_zone = "+00:00"` trying to insert `new Date(0)`.  Ultimately I allowed the column to be nullable and detected values out of range and inserted them as such.

**Comment by dougwilson** [comment]
@techniq we have no intention to replication all edge cases and information from the MySQL server documentation; this module's documentation is only for this module. Trying to insert `1970-01-01 00:00.000Z` into a TIMESTAMP column would result in that error from all libraries and languages, including the MySQL command line prompt itself. Yes, MySQL is quirky.
