### ISSUE TITLE
Circular object in error object 

### ISSUE THREAD

**Issue by goelvivek** [mysqljs/mysql#655]
Hi, 
I am using version mysql@2.0.0-alpha9. The error object returned by module are havine circular refrence. 
If I try to do JSON.stringify it is failing due to the same problem.

**Comment by wootencl** [comment]
I'm having the same issue. I'm using version 2.10.2 currently. I'm trying to select one user from my database for authentication purposes and it works perfectly fine when I do 'SELECT * FROM... WHERE...' but because of how the data is stored in the database I'm trying to retrieve the the cleaner version of a column and thus figured I would just select each column indeiviudally on the row with something like this 'SELECT HEX(ID), FirstName, LastName... WHERE...'. For some reason when I attempt to run this query I'm getting the 'TypeError: Converting circular structure to JSON' error. I'd be glad to provide more details if this you reopen the issue (or start another issue if you want to do that). Thanks for your time and awesome JS client!

**Comment by rajkumarpb** [comment]
> I'm having the same issue. I'm using version 2.10.2 currently. I'm trying to select one user from my database for authentication purposes and it works perfectly fine when I do 'SELECT * FROM... WHERE...' but because of how the data is stored in the database I'm trying to retrieve the the cleaner version of a column and thus figured I would just select each column individually on the row with something like this 'SELECT HEX(ID), FirstName, LastName... WHERE...'. For some reason when I attempt to run this query I'm getting the 'TypeError: Converting circular structure to JSON' error. I'd be glad to provide more details to this if you reopen the issue (or start another issue if you want to do that). Thanks for the awesome JS client!
> 
> EDIT (3.10.16): Resolved the issue. I assumed the problem was occurring in the SQL call as it was throwing a parser error but it was actually because I wasn't setting the property that is used to serialize/deserialize the user when I was doing the testing. A bit of a cryptic error but nonetheless problems solved.

Can you tell me how did you solved it?
