### ISSUE TITLE
Getting time field from a MYSQL table

### ISSUE THREAD

**Issue by ZaidQureshi** [mysqljs/mysql#663]
SO we are using your module for queries that involve fields that are dates/time.The problem is that for a date "2013-10-07" in the database when we query for the dates we are getting "Oct 06 2013 20:00:00 GMT-0400 (Eastern Daylight Time)". I am pretyt sure this is a problem with timezones as MYSQL probably stores in UTC time. Is there a way to fix this??

**Comment by hbi99** [comment]
@dougwilson Your recommendation is not good. In my case, the date stored in mySQL is (and that is what I get from mysql prompt.):
```
2018-02-24
```

When I get the same value via mysqljs, the value returned is:
```
2018-02-23T23:00:00.000Z
```

If I only use the date portion, the date is faulty. In order to get the correct value, the string needs to be evaluated Javascript. Are you doing anything with date values before delivering it?

**Comment by dougwilson** [comment]
Sorry this was left open, didn't see it hanging open. Solution if you want strings (from https://github.com/mysqljs/mysql#connection-options) : `{ dateStrings: ['DATE'] }`
