### ISSUE TITLE
Throw error on connection failed in pool

### ISSUE THREAD

**Issue by Redsandro** [mysqljs/mysql#708]
When I `var pool = mysql.createPool(options);` to a wrong `host` (ip address), I catch nothing in `pool.on('error', function(error) {});`.

Instead, not until I do a `pool.getConnection()` + `connection.query()` and sit out the full (default) timeout of two minutes or something do I receive an `ETIMEDOUT` error.

Is there (or should there be) a way to find out immediately if the connection failed?

In contrast, if I (purposely) specify a wrong username, I immediately catch an `ER_DBACCESS_DENIED_ERROR` error. But a wrong host will just do nothing until the connection times out.

**Comment by Redsandro** [comment]
@dougwilson Sorry for the late response, I was on the toilet.

Indeed I get the a timeout error when specifying this `connectTimeout`.

```
Error: connect ETIMEDOUT
```

Set this to a value higher than 10 seconds and a different hardcoded timeout wins:

```
Error: Handshake inactivity timeout
```

It makes sense, because it should not take that long to connect. When I opened this bug I didn't understand why a timeout was needed at all, but it makes sense. We cannot know that a connection was failed if we do not get a reply from the (non-existing) server. If we connect to an existing server with bad credentials, we get `ER_ACCESS_DENIED_ERROR` immediately, because the server tells us.

I'm satisfied and I forgot to let you know.  :+1: 

So don't change anything on my account.

With that said, I do have the feeling that setting `connectTimeout` should change the time before a `Handshake inactivity timeout` occurs in stead of adding a separate timeout with a separate `connect ETIMEDOUT` error on top of that.

**Comment by dougwilson** [comment]
Hi @Redsandro , the inactivity timeout is not hard-coded in any way. That `Handshake inactivity timeout` is a different timeout tracking a different aspect of the connection, and you control that using the `acquireTimeout` option in your pool options (all pool options are documented at https://github.com/felixge/node-mysql#pool-options).

> With that said, I do have the feeling that setting connectTimeout should change the time before a Handshake inactivity timeout occurs in stead of adding a separate timeout with a separate connect ETIMEDOUT error on top of that.

These are two independent timeouts and track different aspects of the connection lifecycle. They are additive, because they are separate. The `connectTimeout` is a timeout when establishing the underlying TCP connection to your MySQL server. Once this succeeds and you have a TCP channel, then the timeout is destroyed. After that, this module will send a handshake packet to the MySQL server. The `acquireTimeout` will time this aspect of establishing a MySQL application session and the login of your user.

These are separate timeouts because they are very different in nature -- one is sensitive to your networking infrastructure and the other is sensitive to your MySQL application/authentication infrastructure. Typically you want to have a very small `connectTimeout` and a longer `acquireTimeout` (we default to 10s + 10s, which is 20s total).

I hope this helps!

**Comment by Redsandro** [comment]
Thank you for the elaborate response. I get it now. I have no further comments at this time. :smile:

**Comment by nirmalgoswami** [comment]
anyone know solutions of this,,i have same issue

**Comment by vurumadla** [comment]
i am getting a frequent error shown below and it is leading to crash of application.... can anyone help on this.

D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\Parser.js:79
throw err; // Rethrow non-MySQL errors
^

TypeError: Cannot read property 'query' of undefined
at D:\Users\vurumadl\Desktop\bg_latest_5pm\appOriginal.js:671:13
at Handshake.onConnect [as _callback] (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\Pool.js:58:9)
at Handshake.Sequence.end (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
at Handshake.ErrorPacket (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\sequences\Handshake.js:105:8)
at Protocol._parsePacket (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\Protocol.js:280:23)
at Parser.write (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\Parser.js:75:12)
at Protocol.write (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\protocol\Protocol.js:39:16)
at Socket. (D:\Users\vurumadl\Desktop\bg_latest_5pm\node_modules\mysql\lib\Connection.js:104:28)
at emitOne (events.js:96:13)
at Socket.emit (events.js:191:7)
