### ISSUE TITLE
Sync-way of calling .query

### ISSUE THREAD

**Issue by IngwiePhoenix** [mysqljs/mysql#732]
Hey.

I have a rather large callback-hell already. I just wanted to know, if it was possible to return the recieved data instead of delivering it into a callback?

Currently, I wamt to integrate this module into a WS server. Its supposed to read data from the database - via an id, thats also the table's PK - and store it into an internal array. The data is then xml'd and sent to the user.

Or is there a mysql module that does things only in a more sync-way?

Kind regards, Ingwie

**Comment by mrded** [comment]
I'm trying to query 400k rows from a database, by getting 10 at a time. To do that asynchronously I need to use a recursion like this:

```
    var migrate = function(offset, size) {
      Mysql.query(query, [offset, size], function(err, rows) {
        if (!err && rows.length) {
          setTimeout(function() {
            // Pretend doing something and get next batch.
            migrate(offset + size, size);
          }, 1000);
        }
      });
    };

    migrate(0, 10);
```

The problem is, the first call of `migrate()` creates a child callback of itself, and all of them stay in the memory till the last `migrate()` is finished.

The only solution that comes to mind is to run it synchronously inside `while` loop.

Can you please advise how to do that properly? Thanks.

**Comment by dougwilson** [comment]
Hi @mrded until Node.js adds a sync network API we can use, it's not possible to make our `.query` a sync API.

**Comment by olebrun** [comment]
You can wrap query in a Promise and write a "querySync" function.
Then use await (or .then() ) to sequentially run querySync.

var connection = mysql.createConnection();

connection.querySync = function(sql) {
  return new Promise(function(resolve, reject) {
    connection.query(sql, function(error, results, fields) {
      if(error) reject(error);
      else resolve({results, fields})
    })
  })
};

 try {
    var response = await connection.querySync("SQL");
    // do something, you can chain querySync here
  } catch(error) {
    // handle error
  }
