### ISSUE TITLE
Field name in lower case 

### ISSUE THREAD

**Issue by sapkal-manish** [mysqljs/mysql#733]
I have several stored procedures in mysql, which is returning data from table. In this tables all fields have naming convenience as proper case (eg. UserID, UserName, FirstName, LastName ). It is ok when I have retrieve this values using select statement in mysql workbeanch, But If I retrieve using node-mysql, then I want it in lower case. (only column/field name should be convert in lower case). Is it possible or How do I do it? 

I don't want to write field name with alias in select statement.

thanks.

**Comment by johndevedu** [comment]
Sounds like this was a shut case several years back, but I do want to provide a reason why something like this might be desired. It mainly has to do with javascript convention to use camelCasing for variable names, other than cases for Constructors which are PascalCased. I do know that SQL convention is PascalCasing. 

Since mysqljs lib sits in between SQL and JS land, I think it can be reasonable to have this as a feature. I worked using the TediousJS lib (MS-SQL) in the past, and that library had that support built-in (http://tediousjs.github.io/tedious/api-connection.html look for options.camelCaseColumns) so I don't think it's a completely unreasonable idea.

With all that being said, in the meantime, is there an official "filter" process that @sidorares mentioned? Something a la middleware pipeline, or was that just a general reference to adding a function to the callback? Also, is there a way one can add a global query callback that will fire on all queries?
